### ISSUE TITLE
Discussion about default routes

### ISSUE THREAD

**Issue by cbbfcd** [molefrog/wouter#101]
i wrote a [demo](https://codesandbox.io/s/wouter-catch-all-route-3g2fu):

```js
<Switch>
    <Route path="/:anything*">Default Route: nothing found!</Route>
    <Route path="/users/one">Users One</Route>
    <Route path="/">First Route</Route>
     //...
    {/* <Route path="/:anything*">Default Route: nothing found!</Route> */}
</Switch>
```
If we accidentally put the default route in front, it will cause problems.

I think there are two ways:
1. The problem is explained in the documentation, which draws the attention of developers⚠️
2. If you use `<Route default component={AnyComponent}/>` and the position is irrelevant, is it a good idea?

@omgovich @molefrog Looking forward to your reply.

**Comment by omgovich** [comment]
Hi @cbbfcd. I just checked out the react-router and found out that they use the same approach where order matters. So we probably shouldn't change anything in code.

**Comment by molefrog** [comment]
Hey guys! I think we should definitely implement support for `default` prop since a lot of people were asking about that and not everyone gets the `:rest*` trick — it's just not developer-friendly. 

Should the order matter is a good question. Rather than copying it 1-1 from react-router I would first think about possible design choices we would need to make in both cases. 

Let's say the order doesn't matter. Can the Switch then have multiple default routes? I think it can, it's valid, although not a very practical scenario. In this case which one gets rendered: first one, second or both? 

On the other hand, we can just say that default Route is a Route that always matches in a Switch. In this case this:

```js
<Switch>
  <Route default>foo!</Route>
  <Route path="/app">app</Route>
  <Route default>Second default!</Route>
</Switch>
```
Would always render `foo!` no matter what (even if the location is `/app`). And it fits better with the Switch contract "only one child is renderer at most at the time".

**Comment by molefrog** [comment]
To recap.
**Position-independent default Route:**
✔️Possible better DX, although breaks the common "catch-all" mental model from server-side routing
❓Isn't clear how it should behave in edge cases
❓Probably harder to implement and is size-consuming: will need to make an extra iteration over children to determine the first default route

**Position-dependent default Route:**
✔️Follows the same mental model used in RR and server-side routing (Rails, Express, Sinatra etc.)
✔️Doesn't break the Switch contract: 
✔️Should be relatively easy to implement  — add an extra check [here](https://github.com/molefrog/wouter/blob/master/index.js#L132):
```diff
-      (match = matcher(element.props.path, location || originalLocation))[0] 
+      (element.props.default || (match = matcher(element.props.path, location || originalLocation))[0] 
```

So, I would go with the latest. Let me know what you think!

**Comment by omgovich** [comment]
@molefrog I like the **Position-dependent default Route** option.
But I think that most of the users won't understand that `default` means.
Probably they're looking for `404` or `fallback` route.

Also I guess that we should keep in mind common practices that developers used to.
So I have two options to discuss.

### 1. Route without `path`
Instead of defining the new param, just use the same approach as react-router:
> Routes without a path always match.

```
<Switch>
  <Route path="/">Home</Route>
  <Route path="/app">App</Route>
  <Route>404</Route>
</Switch>
```

```diff
-      (match = matcher(element.props.path, location || originalLocation))[0] 
+      (!element.props.path || (match = matcher(element.props.path, location || originalLocation))[0] 
```

### 2. Route with `path="*"`
This is the way to setup default route in `vue-router`.
And it works in `react-router` as well.

```
<Switch>
  <Route path="/">Home</Route>
  <Route path="/app">App</Route>
  <Route path="*">404</Route>
</Switch>
```

```diff
-      (match = matcher(element.props.path, location || originalLocation))[0] 
+      (element.props.path === "*" || (match = matcher(element.props.path, location || originalLocation))[0] 
```

**Comment by cbbfcd** [comment]
> Hey guys! I think we should definitely implement support for `default` prop since a lot of people were asking about that and not everyone gets the `:rest*` trick — it's just not developer-friendly.
> 
> Should the order matter is a good question. Rather than copying it 1-1 from react-router I would first think about possible design choices we would need to make in both cases.
> 
> Let's say the order doesn't matter. Can the Switch then have multiple default routes? I think it can, it's valid, although not a very practical scenario. In this case which one gets rendered: first one, second or both?
> 
> On the other hand, we can just say that default Route is a Route that always matches in a Switch. In this case this:
> 
> ```js
> <Switch>
>   <Route default>foo!</Route>
>   <Route path="/app">app</Route>
>   <Route default>Second default!</Route>
> </Switch>
> ```
> 
> Would always render `foo!` no matter what (even if the location is `/app`). And it fits better with the Switch contract "only one child is renderer at most at the time".

Yep! I just have this idea. I mentioned a related PR before, but I think I can have a better implementation.i will try

**Comment by cbbfcd** [comment]
> @molefrog I like the **Position-dependent default Route** option.
> But I think that most of the users won't understand that `default` means.
> Probably they're looking for `404` or `fallback` route.
> 
> Also I guess that we should keep in mind common practices that developers used to.
> So I have two options to discuss.
> 
> ### 1. Route without `path`
> Instead of defining the new param, just use the same approach as `react-router`.
> 
> > Routes without a path always match [(react-router docs)](https://reacttraining.com/react-router/web/api/Route/path-string-string)
> 
> ```
> <Switch>
>   <Route path="/">Home</Route>
>   <Route path="/app">App</Route>
>   <Route>404</Route>
> </Switch>
> ```
> 
> ```diff
> -      (match = matcher(element.props.path, location || originalLocation))[0] 
> +      (!element.props.path || (match = matcher(element.props.path, location || originalLocation))[0] 
> ```
> 
> ### 2. Route with `path="*"`
> This is the way to setup default route in `vue-router`.
> And it works in `react-router` as well.
> I guess this is the way that users expect.
> 
> ```
> <Switch>
>   <Route path="/">Home</Route>
>   <Route path="/app">App</Route>
>   <Route path="*">404</Route>
> </Switch>
> ```
> 
> We could just change this line:
> 
> ```diff
> -      (match = matcher(element.props.path, location || originalLocation))[0] 
> +      (element.props.path === "*" || (match = matcher(element.props.path, location || originalLocation))[0] 
> ```
> 
> ... or update the matcher.

👍

**Comment by cbbfcd** [comment]
[reach/router](https://github.com/reach/router) Breaking some routines, I think the effect is not bad.

**Comment by cbbfcd** [comment]
Matching the first one is accepted by most people. Following this pattern, Position-dependent may be better, but using `/:any*` is really confusing, I prefer `default` or evev no `path` attribute....

**Comment by molefrog** [comment]
Same here, position-dependent with no path sounds like an ideal option.

**Comment by cbbfcd** [comment]
i will make a PR later !!! 😂

**Comment by cbbfcd** [comment]
@molefrog @omgovich 

in `Route`:
```js
const [matches, params] = match || useRouteMatch;
```
so 
```js
(!element.props.path || (match = matcher(element.props.path, location || originalLocation))[0] 
```

the `match` will be `0`，and this will cause a trouble. 
if i fixed the problem with:

```js
((match = [!element.props.path])[0] ||
(match = match = matcher(element.props.path, location || originalLocation))[0])
```
i can pass all the unit test, but the size limit, and i think this solution is ugly.

**Comment by molefrog** [comment]
Would something like this work:
```js

    if (
      isValidElement(element) &&
      // we don't require an element to be of type Route,
      // but we do require it to contain a truthy `path` prop.
      // this allows to use different components that wrap Route
      // inside of a switch, for example <AnimatedRoute />.
      element.props.path
        ? (match = matcher(element.props.path, location || originalLocation))[0]
        : true
    )
```

**Comment by molefrog** [comment]
```js
(match = (!element.props.path || matcher(element.props.path, location || originalLocation))[0]))
```

**Comment by cbbfcd** [comment]
looks great! The main problem now is the size limit, let me think about it.

**Comment by molefrog** [comment]
@cbbfcd Hey, the feature has finally landed in the new release: https://github.com/molefrog/wouter/releases/tag/v2.5.0

Thanks again for your awesome work on the feature!
