### ISSUE TITLE
Feature list

### ISSUE THREAD

**Issue by cbbfcd** [molefrog/wouter#108]
@molefrog thx first！✌️

because I want to get more involved. so, there are some features you expect for wouter? we all want to know you next plan for wouter.

**Comment by molefrog** [comment]
@cbbfcd There isn't a huge list of new features I'd like to add to wouter. The main reason is it would be nice to maintain the current state of the library size and its capabilities.

There are things however, that our users request quite a lot: like query params etc. For me that was especially tricky to decide if I want to just stop adding new things, or start extending the library heavily.

After giving it some thoughts while I was recovering from my burn out last year (which was the main reason I stopped working actively on it), I've decided that **wouter should support new features through external extendability**. I really like that you can currently specify your custom `useLocation` hook, though not a lot of people are aware of that. But I really want to develop this idea further: wouter is minimalistic by default, but it's extendable, so if you need an extra feature, you can require a separate package for that.

As a example, here is how I see the state support:
```
import { Router, Link } from "wouter";
import locationWithStateHook, { useLocationState }  from '@wouter/use-location-state';

const DisplayCurrentLocationState = () => {
  const state = useLocationState();

  // ... 
}

const App = () => {
   return (
    <Router hook={locationWithStateHook}>
      <Link to="/main" state={{ animate: true }}>Main</Link>
    </Router>
  )
}
```

**Comment by cbbfcd** [comment]
got it! nice idea!
