### ISSUE TITLE
multipath Route

### ISSUE THREAD

**Issue by ozylog** [molefrog/wouter#111]
Hi,

is there anyway i could implement two or more paths in Route component? e.g.
`<Route path={['/u', '/user', '/profile/user']} />`. 
I see wouter supports `path-to-regexp` but i think array of path would be more easy to understand.

Cheers

**Comment by yyynnn** [comment]
+1 
Or match multiple in useRoute(['path', 'path2'])

**Comment by cbbfcd** [comment]
+1 nice idea!

**Comment by molefrog** [comment]
Hey everyone, I put together a demo that demonstrates the multipath routing: https://codesandbox.io/s/wouter-demo-multipath-routes-42bi3?file=/index.js

The idea is that you can customize the function that will be used when a path is matched against the pattern.
