### ISSUE TITLE
`too much recursion` with `useLocation` inside Router `hook`

### ISSUE THREAD

**Issue by silverwind** [molefrog/wouter#112]
https://codesandbox.io/s/wouter-interruptible-transition-ojbkv

Changing the `useLocation` import to a direct ES6 import `wouter/use-location.js` works but this type of import does not work in ES5 environments like `jest`. My current workaround is a local copy of the `useLocation` function.

**Comment by molefrog** [comment]
Hi @silverwind! Sorry I was unavailable, was going trough some burn out recently. I promise I address the issue in the following days and will get back to you with an answer!

**Comment by cbbfcd** [comment]
@silverwind because you used `useLocation`, you should custom your own `useLocation`.

```js
export const useLocation = () => {
  const router = useRouter();
  return router.hook(router); // don't use 'useLocation' in your hook.
};
```

**Comment by molefrog** [comment]
> Changing the useLocation import to a direct ES6 import wouter/use-location.js works but this type of import does not work in ES5 environments like jest

Might be related to #126. There is a PR https://github.com/molefrog/wouter/pull/127 already that should fix the CJS subpath import.

**Comment by molefrog** [comment]
The recursion is expected, since `useLocation` imported from `wouter` is different from `wouter/use-location`. It's probably a bad naming, ideally they should be named:
- `import { useLocation } from "wouter"` — returns current router's location
- `import useBrowserLocation from "wouter/use-browser-location"` — a standalone hook that react on History API changes.

I've got a feeling that once we fix the #126, you should be able to use the code in ESM and CJS, without having a local copy of the hook.

**Comment by silverwind** [comment]
Rename sounds good to avoid confusion. Would it be possible to just export this `useBrowserLocation` as a named export from `wouter` maybe?

**Comment by molefrog** [comment]
> Would it be possible to just export this useBrowserLocation as a named export from wouter maybe?
Once we release #127, you will be able to import it as intended using `import from "wouter/use-location"`.

**Comment by silverwind** [comment]
Fine with it if it works in Jest. Personally I'm not much of a fan of path imports in general thought, I much prefer named exports 😉.

**Comment by molefrog** [comment]
Should work now with [v2.5.1](https://github.com/molefrog/wouter/releases/tag/v2.5.1).

**Comment by Bonfims** [comment]
> > Would it be possible to just export this useBrowserLocation as a named export from wouter maybe?
> 
> Once we release #127, you will be able to import it as intended using `import from "wouter/use-location"`.

Hello, with version 3 i getting error "Missing "./use-location" specifier in "wouter" package", something change?

**Comment by molefrog** [comment]
Yeah, we moved it to `wouter/use-browser-location` for clarity and to distinguish from other location hooks (like hash location). See this https://github.com/molefrog/wouter/releases/tag/v3.0.0

**Comment by Bonfims** [comment]
> Yeah, we moved it to `wouter/use-browser-location` for clarity and to distinguish from other location hooks (like hash location). See this https://github.com/molefrog/wouter/releases/tag/v3.0.0

thank you, it worked!
