### ISSUE TITLE
make static-location more useful for testing

### ISSUE THREAD

**Issue by davidje13** [molefrog/wouter#113]
Importing `wouter/static-location` is useful for server-side rendering, and also has some use when testing (e.g. ensuring the correct components are rendered for a given path). But it is lacking the ability to record changes to the URL (e.g. from redirects, links, or more generally `setLocation`).

Adding a small amount of state to this would make it more useful for testing, while maintaining its applicability to static rendering. In my own project, I have added the following, which could easily be included here as a replacement to `static-router`.

```ts
import type { LocationHook, Path } from 'wouter';

export interface StaticLocationHook extends LocationHook {
  locationHistory: Path[];
}

export default function staticLocationHook(
  path = '/',
  dynamic = false,
): StaticLocationHook {
  let latestLocation = path;

  const hook: StaticLocationHook = () => [
    dynamic ? latestLocation : path,
    (to: Path, replace?: boolean): void => {
      if (replace) {
        hook.locationHistory.pop();
      }
      hook.locationHistory.push(to);
      latestLocation = to;
    },
  ];

  hook.locationHistory = [path];
  return hook;
}
```

This allows testing like so:

```ts
const locationHook = staticLocationHook('/');

const dom = render((
  <Router hook={locationHook}>
    <MyComponent />
  </Router>
), { queries });

// (click a link)

expect(locationHook.locationHistory).toEqual(['/', '/my-new-path']);
```

And to perform transition tests, `dynamic` can be set true, causing the page to navigate realistically when links are clicked, etc.

**Comment by molefrog** [comment]
@davidje13 Awesome work! This definitely looks like something we could add to the library.

**Comment by cbbfcd** [comment]
add a fake 'history' 🚀

**Comment by davidje13** [comment]
Want me to put together a PR? I'm guessing the necessary bits would be implementation (as shown here), typescript declaration, tests, and documentation updates in the readme?

**Comment by molefrog** [comment]
@davidje13 Sure, I would appreciate you sending a PR. Let's discuss an API in details. Here are my thoughts.

- Since `staticLocation`'s main use case is SSR, it would be a bit risky to make the history recording functionality on by default. The recording is mostly needed in tests, so I assume something like this `staticLocationHook({ record = false })` should work.
- I like the idea of making the hook dynamic `staticLocationHook({ record = false, dynamic = false })`, however it just feels a bit unnatural that the name of the hook is static, but it can act as dynamic under certain circumstances. Taking this into an account, would that be better if we leave the staticLocation as is and implement another hook `/test-location.js` with the following API:

```js
// test-location.js

// a factory method that returns a test location hook
// usage:
// const hook = createTestLocation('/app');
// <Router hook={hook} />
// hook.history // ['/app', /users']

export default function createTestLocation(path = '/', { record = true } = {}) {

}
```

P.S. I also prefer `hook.history` since it's shorter 😄 

Let me know what you think about that!

**Comment by davidje13** [comment]
It can be useful in tests to have changes recorded but not acted on, so I'd rather keep the ability to switch `dynamic` on and off.

Note that this functionality isn't limited to tests; presumably any statically-rendered page which causes a navigation is expecting to perform a redirect, in which case I'd want to be able to capture that info and send it as a 3xx or similar. I could imagine somebody writing code like:

```js
const locationHook = staticLocationHook(requestedPage);

const dom = render(<Router hook={locationHook}><App /></Router>);

if (locationHook.history.length > 1) {
  return Redirect(locationHook.history[1]);
} else {
  return Ok(dom);
}
```

But if you want to separate this from the existing `staticLocationHook` then fair enough. But maybe name the new one `inMemoryLocationHook` / `capturingLocationHook` / `recordingLocationHook` / `historyLocationHook` or even just `locationHook`?

I'll put a PR together which can be used for further discussion; the core concepts won't be affected much, it's just a case of figuring out an API.

**Comment by molefrog** [comment]
> It can be useful in tests to have changes recorded but not acted on, so I'd rather keep the ability to switch dynamic on and off.

I agree. One the initial versions was `staticLocationHook(initalPath, { record:, dynamic: })` where both of these things are supported. 

> Note that this functionality isn't limited to tests; presumably any statically-rendered page which causes a navigation is expecting to perform a redirect, in which case I'd want to be able to capture that info and send it as a 3xx or similar. I could imagine somebody writing code like

Oh, I see now, that is an interesting case. Initially, I was concerned about the fact that the hook is used on a server and potentially could stay alive between multiple requests. But now I realize that this isn't true: you usually call the factory method on every request, so the new copy of the hook is created.

> But if you want to separate this from the existing staticLocationHook then fair enough.
You know, considering your arguments, having these things implemented in `staticLocation` isn't such a bad idea. And I really don't want to have too many files in the repo 😄 Let's go with the `staticLocationHook(initialPath, { record = false, dynamic = true })` version.

**Comment by molefrog** [comment]
@davidje13 Released in https://github.com/molefrog/wouter/releases/tag/v2.5.0

Thanks again for such an amazing work!
