### ISSUE TITLE
Add `replace` option to `Redirect`

### ISSUE THREAD

**Issue by davidje13** [molefrog/wouter#114]
The existing `Redirect` component acts as a simple wrapper around `setLocation`, but only supports the first argument. It would be convenient if the `replace` argument were also supported, since a common use-case for instantaneous redirects is to fix old links (where keeping the old path in the history causes problems when users attempt to navigate back).

This is easy to add:

```js
export const Redirect = props => {
  const [, push] = useLocation();
  useLayoutEffect(() => {
    push(props.href || props.to, props.replace);

    // we pass an empty array of dependecies to ensure that
    // we only run the effect once after initial render
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  return null;
};
```

```ts
export type RedirectProps = NavigationalProps & {
  replace?: boolean;
  children?: never;
};
```

**Comment by molefrog** [comment]
The main work was done here https://github.com/molefrog/wouter/pull/121
I'm going to polish the code a little bit and make a new release soon.

**Comment by molefrog** [comment]
Released in https://github.com/molefrog/wouter/releases/tag/v2.5.0
