### ISSUE TITLE
Previous url in the navigation of the website

### ISSUE THREAD

**Issue by VyseClown** [molefrog/wouter#115]
Hi!

My doubt would be if I can detect the previous link that the user of my site was on, the useLocation hook has a const that stores the last address, and I would like to access that

**Comment by molefrog** [comment]
Ok, I think I got the idea. I can imagine that the following hook would solve it:

```js
const usePrevLocation = () => {
  const [location] = useLocation();
  const [prevLocation, setPrevLocation] = useState(null);
  const lastSavedLocation = useRef(null); // temp buffer

  useEffect(() => {
    // this function will be called each time the location changes
    setPrevLocation(lastSavedLocation.current)

    lastSavedLocation.current = location
  }, [location])

  return prevLocation
}
```

(I haven't tested it, but the idea is to subscribe to location change and use the temp value to hold the last used location).
