### ISSUE TITLE
How to Lazy load a route?

### ISSUE THREAD

**Issue by fuadnafiz98** [molefrog/wouter#116]
is there any way to add lazy loading or route based code splitting with `preact-wouter`?
there is `preact-async-route` for async routing but it is for `preact-router`, do you have any recommended way to do code splitting with this library?

**Comment by pmkroeker** [comment]
If you're using preact 10, you can leverage `Suspense`. This is what I do.

```tsx
import { Router } from 'wouter-preact';
import { Suspense, lazy } from 'preact/compat';

const Home = lazy(() => import('./Home'));
...

<Router>
  <Suspense path='/home' fallback={<Loading />}>
    <Home />
  </Suspense>
</Router>
```

**Comment by fuadnafiz98** [comment]
thanks :)

**Comment by aguilera51284** [comment]
its suspense for each route ? sorry for comment xD

**Comment by pmkroeker** [comment]
Yes, the path must be on the child of the router not the grandchild.
