### ISSUE TITLE
Redirect to sub static app

### ISSUE THREAD

**Issue by JohanMouchet** [molefrog/wouter#117]
Hi there,

Here is some context first:
- I'm developing an SPA [site](https://www.johan-mouchet.com/). The source is available on [GitHub](https://github.com/JohanMouchet/johan-mouchet.com)
  - it's bootstrapped with CRA with serviceWorker enabled
- In parallel I have a Storybook app, that I build as a static app to a subfolder of my SPA with this script: `"react-scripts build && build-storybook -c .storybook -o build/storybook"`
- I'm handling the rooting like so:
  - a Netlify `_redirects` file redirects all traffic to `index.html`: `/* /index.html 200`
  - and the front-end routing is done through [wouter](https://github.com/molefrog/wouter):
  ```
  <Switch>
    <Route path="/">Home</Route>
    <Route path="/storybook/*">
      <Redirect to="/storybook/" />
    </Route>
    <Route path="/:rest*">NotFound</Route>
  </Switch>
  ```
  - You can see I'm explicitly defining a `/storybook/*` route as without it, it would directed to the `/:rest*` one

- When I test the production build locally with `npx http-server build/`:
  - the Home page (`/`) works
  - the NotFound page (`/unknown-page`) doesn't. Which would make sense because `_redirects` is an Netlify feature
  - the Storybook app works (`/storybook/`)

This issue I'm facing is:
- When I deploy to Netlify
  - the Home page (`/`) works
  - the NotFound page (`/unknown-page`) works (redirects to NotFound)
  - but the Storybook app (`/storybook/`) **doesn't**, it renders the "NotFound"
    - more surprisingly, if I hard reload the page, it works

My questions is:
**Why isn't the redirect to the static subfolder app working?**

Side note, thanks to the wouter team for this awesome library. 👏

**Comment by molefrog** [comment]
Hi @JohanMouchet !
> Side note, thanks to the wouter team for this awesome library. 👏
Very much appreciate that 😊 

So, how does your `_redirects` file look like? I assume that the reason `/storybook/` route works in dev is because the http-server figures it is an existing folder so it serves `build/storybook/index.html` instead of `build/index.html`, right? (not familiar with Storybook, but I can guess it creates a seperate html entry point).

**Comment by molefrog** [comment]
I just figured that the reason you want to have the redirect in your main React app is because you have links to your Storybook inside of the app. If that's correct, then I'm afraid it won't work, simply because wouter's redirect is done without reloading the page. You might just need a regular `<a>` links instead, or you can perform an html redirect using in JS with `window.location = "/storybook"`.

**Comment by molefrog** [comment]
The thing is your dealing here with two separate routers: one is Netlify that decides which file is to serve when you type an address in your browser, and second is wouter which is only running as long as your main React SPA is running. The redirect that Wouter does will only affect the app's state and the URL in the address bar (see [HTML5 history API for reference](https://css-tricks.com/using-the-html5-history-api/)), but it won't trigger the page refresh.

If you need to redirect to an another html page you need to tell the browser to refetch the page, the simpliest way to do so is to use plain-old `<a />` link navigation. Hope it helps!

**Comment by JohanMouchet** [comment]
Hi @molefrog,

Thank you for your detailed answer.

> I assume that the reason `/storybook/` route works in dev is because the http-server figures it is an existing folder so it serves `build/storybook/index.html` instead of `build/index.html`, right?

You're correct, there is an `index.html` file in `build/storybook/`. I too think `http-server` figures this out.

> The thing is your dealing here with two separate routers

You understood the ambiguous challenge.

There are actually two use cases I'm trying to solve:
1. One, as you said, is to be able to link from the main app to Storybook with a `<a>` tag
2. Another is to enter the storybook URL into the browser navigation bar

In both cases:
- It works when explicitly defining: `storybook/index.html`.
- It doesn't work with `/storybook/` (the preferred way)

>  The redirect that Wouter does will only affect the app's state and the URL in the address bar (see HTML5 history API for reference), but it won't trigger the page refresh.

Just to confirm, does it means the above cannot be resolved?

**Comment by molefrog** [comment]
> Just to confirm, does it means the above cannot be resolved?
I assume the problem is in the Netlify redirects configuration and it's not related to wouter.

What I can recommend from looking at your code snippet is to use a custom page-reload redirect component and use named wildcard segments (`:any*`, wouter does not support just wildcards).

```js
const FullPageRedirect = ({ to }) => {
   useEffect(() => window.location = to, []);
   return null;
}

// when you navigate to /storybook/foo in your SPA app, it gets you redirected to the Storybook
// by doing a page reload 
const App = () =>
  <Switch>
    <Route path="/">Home</Route>
    <Route path="/storybook/:rest*">
      <FullPageRedirect to="/storybook/" />
    </Route>
    <Route path="/:rest*">NotFound</Route>
  </Switch>
```

**Comment by JohanMouchet** [comment]
I had a try at the page-reload redirect, but it created an infinite loop unfortunately.

No worries, `/storybook/index.html` will do fo now.

Thank you for taking the time to investigate this peculiar double routing scenario.
Keep up the good work with wouter 👍
