### ISSUE TITLE
react-router bundle size

### ISSUE THREAD

**Issue by gitcatrat** [molefrog/wouter#130]
> Zero dependency, only 1308 bytes gzipped vs 17KB React Router.

Not sure if outdated information or something else (not excluding my own error) but react-router is about 11Kb in my estimations, not 17Kb. Not a huge difference by itself but relatively it is.

Total 19.84Kb, preact of it is 8.2Kb. These are not hyper exact sizes but accurate enough.

<img width="1541" alt="bundle" src="https://user-images.githubusercontent.com/58787197/89127677-17882e00-d4f8-11ea-8db7-262d65c5bfb3.png">

By the way, I love what you're doing. 

I'm in the middle of app diet myself and I would have jumped on wouter train ASAP but I do a lot of fancy stuff with urls and the absence of Link API (particularly `state`) and history of last navigation unfortunately puts a stop to my conversion. 

```jsx
<NavLink
  className={props.className}
  activeClassName={active}
  exact={props.exact || true}
  to={{
    pathname: to,
    // search: "?sort=name",
    // hash: "#the-hash",
    state: state
  }}
/>
```

**Comment by molefrog** [comment]
@gitcatrat Thanks, that info was probably outdated. I fixed the README.

Regarding your transition: I know, the state/search support has been requested multiple times. Good news is I'm planning to release an improved useLocation hook soon that will allow to specify state and other navigation parameters. Stay tuned!
