### ISSUE TITLE
Scroll to top on route change

### ISSUE THREAD

**Issue by notangelmario** [molefrog/wouter#132]
How can we make the page scroll back to top on route change? Is there a function we can hook into the Link component? Some kind of option or something

**Comment by molefrog** [comment]
@notangelmario The solution should probably similar to what they recommend in react-router: https://reactrouter.com/web/guides/scroll-restoration/scroll-to-top

```js
import { useEffect } from "react";
import { useLocation } from "wouter";

export default function ScrollToTop() {
  const { pathname } = useLocation();

  useEffect(() => {
    window.scrollTo(0, 0);
  }, [pathname]);

  return null;
}
```

**Comment by notangelmario** [comment]
Thank you very much!

**Comment by xav-ie** [comment]
Just wanted to note that the solution above is outdated:
```jsx
import { useEffect } from "react";
import { useLocation } from "wouter";

export default function ScrollToTop() {
  const  [ pathname ] = useLocation();

  useEffect(() => {
    window.scrollTo(0, 0);
  }, [pathname]);

  return null;
}
```
Simply change the curly braces to square brackets and you are set!

**Comment by molefrog** [comment]
I've updated my comment, thanks for noticing the typo @xav-ie
