### ISSUE TITLE
simple way to "history.push" in a React Component?

### ISSUE THREAD

**Issue by Khorkhe** [molefrog/wouter#135]
I'm coming here after the frustrations from React Router's repeated breaking changes between their major versions with complete disregard for existing project built atop of it, and am looking to have a simple way to, from within a React Component, push a new URL.

More specifically, the React Component is a ReduxForm, with a submit handling function:
```
class LoginForm extends React.Component {
  submit = (values) => {
    let email = values.email;
    let password = values.password;
    ...
    axios.post('/login', {
      email: email,
      password: password
    })
    .then((response) => {
      //...
      // push new route   
    }
  
  render
  <Stuff/>
```

Trying to use UseLocation, it won't allow me to within a component.
I see the Redirect component, but not sure how it would be used inside a promise response.

Any suggestions without having to convert all my classes to functions?

**Comment by molefrog** [comment]
Hi @Khorkhe! While hooks aren't designed to run inside class components, there are well-known tricks that allow you to do that. It is actually not wouter-specific, you can use the trick with any other hook essentially.

Basically, this can be achieved with either:
- high-order functions
- render-prop components
- context 

I put together a small demo to illustrate the first one: https://codesandbox.io/s/wouter-class-components-czsdm

```js
import React, { Component } from "react";
import { Route, Link, useLocation } from "wouter";

// A high-order component that allows to use useLocation inside class components
const withUseLocation = (Component) =>
  React.forwardRef((props, ref) => {
    const useLoc = useLocation();

    return <Component {...props} ref={ref} useLocation={useLoc} />;
  });

class HomeComp extends Component {
  render() {
    const [location, navigate] = this.props.useLocation;

    return (
      <div>
        Hi! This is a class component that uses hooks. Current location is{" "}
        {location}, <button onClick={() => navigate("/about")}>Change</button>
      </div>
    );
  }
}

// you need to wrap your class component with the high-order function in order
// to have `useLocation` available in props
const Home = withUseLocation(HomeComp);
```

**Comment by molefrog** [comment]
Closing the issue, as it isn't directly related to wouter functionality.
