### ISSUE TITLE
[bug] Case sensitive path

### ISSUE THREAD

**Issue by shovelmn12** [molefrog/wouter#145]
After the new update 2.5.2 i got issue with case sensitivity.
its important to me because i am using firestore and using the doc id as path, doc id is case sensitive in firestore.

after digging around in your code i fount the problem at last :)

https://github.com/molefrog/wouter/blob/bb77e3fefe9275aaa352448abe596308e12f2c29/use-location.js#L69
https://github.com/molefrog/wouter/blob/bb77e3fefe9275aaa352448abe596308e12f2c29/use-location.js#L70

the `.toLowerCase()` messed my app really bad.

as you can see pre 2.5.2:

https://github.com/molefrog/wouter/blob/9d502e8b10103bb012ee143064167b4a9f61efc6/use-location.js#L71
https://github.com/molefrog/wouter/blob/9d502e8b10103bb012ee143064167b4a9f61efc6/use-location.js#L72

no `.toLowerCase()`

suggestion to fix:
add an optional caseSensitive true|false in useLocation, quick and easy fix.
or just remove `.toLowerCase()` and each user will decide how to set routes (case sensitive or not) - better option in my opinion

**Comment by molefrog** [comment]
@shovelmn12 Thanks for reporting! I guess the best way to solve this is to write a function that removes the basepath case-insensitive. Example:

```js
"/APP/users" - "/app" => "/users"
"/ApP/users/JohnDoe" - "/app" => "/users/JohnDoe"
```

I expect to have a fix soon!

**Comment by molefrog** [comment]
cc @cbbfcd

**Comment by molefrog** [comment]
@shovelmn12 Fixed via https://github.com/molefrog/wouter/commit/cb0b84760d4c0d5d27932bc604e388802746dde7 and release in v2.5.3

**Comment by shovelmn12** [comment]
I think you shouldn't have toLowerCase at all there..
Think about it if someone want to have 2 different paths for
'/app/users or /App/Users'
he wouldn't be able to get it with .toLowerCase...

Again i think you should just remove the toLowerCase and let users decide

BTW urls suppose to be case sensitive...

**Comment by molefrog** [comment]
> BTW urls suppose to be case sensitive...
They are! But wouter as well as react-router are designed to have case-insensitive route matching algorithm by default. The main benefit of that I guess is that case-insensitive URLs are better for SEO (if someone posts a link to an ecommerce shop shop.com/PRoduct/1, the visitors will still be able to reach that page despite the case). That's the reason we decided to make the base path case-insensitive as well in the first place.

> Think about it if someone want to have 2 different paths for
> '/app/users or /App/Users'
> he wouldn't be able to get it with .toLowerCase...
They could achieve that using custom matchers https://codesandbox.io/s/wouter-path-to-regexp-case-sensitive-r15s5?file=/src/index.js

**Comment by shovelmn12** [comment]
I meant with base and case sensitive but when i am thinking about it now it might not really be a usable case.
ill let you know if i figure it out
