### ISSUE TITLE
Unpkg UMD version of Wouter-Preact

### ISSUE THREAD

**Issue by jpguzman** [molefrog/wouter#149]
Hello, is there a way to get a UMD version of Wouter-Preact on unpkg? All I see is a common js version.
Thank you!

**Comment by molefrog** [comment]
Hi @jpguzman 
May I ask what kind of exports does your app expect? Is it AMD or ES modules? The later should be supported through Skypack CDN https://cdn.skypack.dev/wouter-preact

As for AMD and UMD, we didn't plan to support them, as we're trying to make our dist as tiny as possible.

**Comment by molefrog** [comment]
Any updates on this one?
