### ISSUE TITLE
Getting active path

### ISSUE THREAD

**Issue by stsourlidakis** [molefrog/wouter#15]
Hello, wouter seems great so far!

I would like to highlight the current page's link on my navbar, is there a better way than the following?

```js
const [, params] = useRoute("/:page");
const currentPage = params ? `/${params.page}` : "/"; //params will be null on /
```

**Comment by molefrog** [comment]
Sure, there is a better way. The `useRoute` hook returns a boolean value, which shows if there was a match. So basically you could extend the current link's behaviour like: https://github.com/molefrog/wouter/pull/17/files

Although I'm still considering if the NavLink should become a part of the package. These types of behaviours are usually quite easy to implement yourself.

**Comment by molefrog** [comment]
Hey @stsourlidakis I have prepared a code sandbox that illustrates a use of `ActiveLink`: https://codesandbox.io/s/5zjpj19yz4. 

I could potentially add this behaviour to the current `Link` component, but this will lead to unnecessary use of context/state in every Link component (unfortunately, you can't place a hook inside a condition). So the only work around is to introduce a new component, but I would rather include it in `extra/` folder.  I'm going to update the README with the list of code recipes and demos.
