### ISSUE TITLE
Many exports not found

### ISSUE THREAD

**Issue by johnrichardrinehart** [molefrog/wouter#150]
I'm trying to use `wouter` in place of `react-router`. I'm having problems soon as I import anything from the `wouter` package. I get 18 errors that look like the below. I've reproduced a minimum working example in [this repository] (https://github.com/johnrichardrinehart/wouter). To reproduce locally it should be sufficient to `git clone` that repository and then `yarn run`. Please note that I'm using `yarn berry`. So, a hopefully comprehensive set of instructions to reproduce would be:
1. `git clone https://github.com/johnrichardrinehart/wouter`
1. `yarn set version berry` (assuming `yarn` is installed already)
1. `yarn install` (dependencies are cached in my repo, but it's good to make sure)
1. `yarn run build` (look at all the errors... should look like below)

Please let me know what I can do to help us debug this issue.

```
ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 23:18-31
export 'createContext' (imported as 'createContext') was not found in './react-deps.js' (possible exports: )
 @ ./src/index.js 4:0-31 7:42-47

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 32:20-30
export 'useContext' (imported as 'useContext') was not found in './react-deps.js' (possible exports: )
 @ ./src/index.js 4:0-31 7:42-47

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 51:17-23
export 'useRef' (imported as 'useRef') was not found in './react-deps.js' (possible exports: )
 @ ./src/index.js 4:0-31 7:42-47

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 63:14-20
export 'useRef' (imported as 'useRef') was not found in './react-deps.js' (possible exports: )
 @ ./src/index.js 4:0-31 7:42-47

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 70:9-10
export 'createElement' (imported as 'h') was not found in './react-deps.js' (possible exports: )
 @ ./src/index.js 4:0-31 7:42-47

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 85:24-25
export 'createElement' (imported as 'h') was not found in './react-deps.js' (possible exports: )
 @ ./src/index.js 4:0-31 7:42-47

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 97:22-33
export 'useCallback' (imported as 'useCallback') was not found in './react-deps.js' (possible exports: )
 @ ./src/index.js 4:0-31 7:42-47

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 121:14-28
export 'isValidElement' (imported as 'isValidElement') was not found in './react-deps.js' (possible exports: )
 @ ./src/index.js 4:0-31 7:42-47

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 121:52-53
export 'createElement' (imported as 'h') was not found in './react-deps.js' (possible exports: )
 @ ./src/index.js 4:0-31 7:42-47

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 123:9-21
export 'cloneElement' (imported as 'cloneElement') was not found in './react-deps.js' (possible exports: )
 @ ./src/index.js 4:0-31 7:42-47

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 136:6-20
export 'isValidElement' (imported as 'isValidElement') was not found in './react-deps.js' (possible exports: )
 @ ./src/index.js 4:0-31 7:42-47

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 145:13-25
export 'cloneElement' (imported as 'cloneElement') was not found in './react-deps.js' (possible exports: )
 @ ./src/index.js 4:0-31 7:42-47

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 155:2-17
export 'useLayoutEffect' (imported as 'useLayoutEffect') was not found in './react-deps.js' (possible exports: )
 @ ./src/index.js 4:0-31 7:42-47

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/react-deps.js 1:0-12:15
Module not found: Error: Can't resolve 'react' in '/home/john/Downloads/repos/temp/.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter'
Did you mean 'index.js'?
BREAKING CHANGE: The request 'react' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
 @ ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 4:0-13:25 23:18-31 32:20-30 51:17-23 63:14-20 70:9-10 85:24-25 97:22-33 121:14-28 121:52-53 123:9-21 136:6-20 145:13-25 155:2-17
 @ ./src/index.js 4:0-31 7:42-47

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/use-location.js 12:25-33
export 'useState' (imported as 'useState') was not found in './react-deps.js' (possible exports: )
 @ ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 1:0-45 26:9-21
 @ ./src/index.js 4:0-31 7:42-47

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/use-location.js 13:19-25
export 'useRef' (imported as 'useRef') was not found in './react-deps.js' (possible exports: )
 @ ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 1:0-45 26:9-21
 @ ./src/index.js 4:0-31 7:42-47

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/use-location.js 15:2-11
export 'useEffect' (imported as 'useEffect') was not found in './react-deps.js' (possible exports: )
 @ ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 1:0-45 26:9-21
 @ ./src/index.js 4:0-31 7:42-47

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/use-location.js 40:19-30
export 'useCallback' (imported as 'useCallback') was not found in './react-deps.js' (possible exports: )
 @ ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 1:0-45 26:9-21
 @ ./src/index.js 4:0-31 7:42-47

webpack 5.9.0 compiled with 18 errors in 888 ms
```

**Comment by molefrog** [comment]
Could be related to https://github.com/webpack/webpack/issues/11467#issuecomment-691702706

**Comment by molefrog** [comment]
After some digging, I found that the issue is most probably in yarn/berry and the way it packages dependencies. If I install it with regular Yarn, everything works fine. 

The source of the problem: wouter declares itself as `"type": "module"` in `package.json`, which means that all the relative import must have an extension:
```js
import foo from "./foo" // will not work!
import foo from "./foo.js" // this will
```

And if you look at the source code of the library, we follow that rule. However, when it comes to the third-party dependencies like "react" there is no way to use a full path to the file. Node.js figures that and processes third-party imports differently.  
It seems like for some reason Webpack thinks that "react" is local file rather than a package. 

I would recommend looking at this thread:
https://github.com/webpack/webpack/issues/11467#issuecomment-735347195

**Comment by johnrichardrinehart** [comment]
I tried all of the suggestions in webpack/webpack#11467 but I had no luck.

I've filed yarnpkg/berry#2194 because I have no idea what the problem is.

**Comment by molefrog** [comment]
@johnrichardrinehart There is one approach you can use in order to make sure it isn't wouter's issue: find another package that comes with ES-modules exports (basically, its `package.json` should contain `"type": "module"`) and import it in your playground. 
https://github.com/Polymer/lit-element ?

**Comment by johnrichardrinehart** [comment]
I'm importing another package that's doing something similar. It [has something like](https://github.com/britecharts/britecharts-react/blob/8f3d1a32fffae0c56524523db57ddfa51f47de74/package.json#L5)

`,
"module": <path>,
`
in its `package.json`. So, no `root.type === "module"` but `root.module == <path>`. Does `root.module` being set to a `string` automatically configure the `type` as a `module`?

**Comment by molefrog** [comment]
That isn't the same. `module: "path"` is a non-standard way of telling where Webpack (or any other bundler that follows the same convention) could find a source with ES-module style imports.

`type: "module"` at the other hand, is a Node.js standard of declaring that the package uses ES-module import/exports:
https://nodejs.org/api/packages.html#packages_node_js_package_json_field_definitions

**Comment by johnrichardrinehart** [comment]
> is a non-standard way of telling Webpack ...

Okay, I looked at the reference you sent me. I'm still not clear on whether CommonJS or ES Modules are the preferred way of developing JavaScript libraries moving forward (or if they each have their place), but I understand the role of "type" and "module" root-level keys.

I just tried `berry` with `Poylmer/lit-element` against the latest version (2.4.0, which includes ` type: module` in its `package.json`). [No issues](https://github.com/johnrichardrinehart/wouter/commit/844e15ec672cc77e151da61ba8b47fe4ecf05c19).

**Comment by johnrichardrinehart** [comment]
Okay, this was a `webpack` configuration problem. I had two issues, so that link didn't provide my entire solution. I had to remove `<root>.module.rules.exclude = /node_modules/` which was inhibiting some module resolution base on path. I also needed to add `<root>.module.rules.resolve = {fullySpecified: false}`. So the relevant portion of `webpack.config.js` now looks like

```js
module.exports = {
  mode: "development",
  // The below key:object format is used to force the css faile to be named "index.css" instead
  // of the default "main.css"
  // C.f.: https://github.com/webpack/webpack/blob/d870365/lib/EntryOptionPlugin.js#L44
  // and https://stackoverflow.com/questions/60139960/why-is-name-always-main-in-minicssextractplugin-for-webpack
....................
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        resolve: {fullySpecified: false},
        use: {
          loader: "babel-loader"
        }
      },
    ]
  },
....................
};
```

**Comment by johnrichardrinehart** [comment]
I've reviewed your repository. You conform to the latest standard in using extensions on your local imports. I'm not sure why `webpack` thinks it's a local import. I'll flag an issue over there if I can't figure out what's going on.

Thanks for your help @molefrog . Sorry to bother you with an issue that wasn't your fault.

**Comment by molefrog** [comment]
Not at all @johnrichardrinehart! Thanks for bringing this up and glad you found the root of the problem 😄 

Happy wouting!

**Comment by johnrichardrinehart** [comment]
In case you're awake and want to do this before I can: https://github.com/webpack/webpack/issues/12093#issuecomment-736587220 .

**Comment by johnrichardrinehart** [comment]
Yarn devs have managed to resolve this by modifying your package.json. https://github.com/yarnpkg/berry/issues/2199#issuecomment-736681587

What's the purpose of defining the module exports in package.json ?
