### ISSUE TITLE
Route "/" in scoped Router matches routes outside scope

### ISSUE THREAD

**Issue by jvdsande** [molefrog/wouter#152]
Hi!

Thanks for Wouter, this is an amazing piece of hook-based technology :) So elegant yet so powerful.

I've stumbled across an issue while using scoped Router (`<Router base="/my/base/path" />`)

Basically, the problem is that inside such a Router, any path _not starting with /my/base/path_ will still match the `"/"` path. For instance :

```js
function MyScopedApp() {
   return (
       <Router base="scope">
           <Switch>
                <Route path="/subpage">    {/* Correctly only renders when path is `/scope/subpage'` */}
                     <SubPage />
                </Route>
                
                <Route path="/">    {/* Incorrectly renders when path is `/outofscope/whatever` */}
                     <HomePage />
                </Route>
           </Switch>
       </Router>
   )
}
```

Most of the time this would not be an issue, since `MyScopedApp` is most likely itself wrapped in a catch-all route scoped with the base path.

But if "HomePage" for some reason manipulates the location, it _will_ render once before being unmounted by its parent scoped Route. This causes an issue with the following setup:

```js
function MyScopedApp() {
   return (
       <Router base="/scope">
           <Switch>
                <Route path="/subpage1">
                     <SubPage1 />
                </Route>
                <Route path="/subpage2">
                     <SubPage2 />
                </Route>
                
                { /* Redirect /scope to /scope/subpage1 */ }
                <Route path="/">
                     <Redirect to="/subpage1" replace />
                </Route>
           </Switch>
       </Router>
   )
}
```

What this wants to achieve is, when a user navigates to `/scope`, `MyScopedApp` is rendered, and automatically redirects to `/scope/subpage1`.

The redirect on first navigation happens correctly, but the app is now soft-locked inside `/scope/subpage1`, because any attempt to navigate to `/outofscope` will match the `Redirect`'s wrapping `Route`, thus triggering the `Redirect` itself.

**Additional information**

This behavior is seen across any match-related situation. For instance:

````js
// Inside a scoped router on "/scope", when pathname is currently "/outofscope"
const [location] = useLocation()  
console.log(location) // "/", should be null/undefined most likely? Or even "../outofscope"

const [match] = useMatch("/")
console.log(match) // true, should be false
````

I guess this could be fixed by using a custom matcher on my scoping Router, but I feel like this behavior is somewhat not what other users would expect either, so maybe it should be fixed in the default matcher directly.

**Comment by jvdsande** [comment]
I might experiment a bit more, maybe today, try to modify wouter's code to see if this can easily be fixed. I could then open a PR if you want.

In the meantime for anyone stumbling across this issue, the solution for now is to hoist the Redirect out of the scoped Router, and have its Route match '/scope' instead of '/'

**Comment by molefrog** [comment]
Hi @jvdsande thanks for the detailed description.
As far as I remember, the `useLocation()` hook should return the original path unmodified if it is located outside of the base scope:

```js
// Inside a scoped router on "/scope", when pathname is currently "/outofscope"
const [location] = useLocation()  // this should return "/outofscope", not "/", right?
```

This is probably due to how this method is implemeted: https://github.com/molefrog/wouter/blob/master/use-location.js#L73

I agree that it could create some weird behaviour indeed when you have more just one app mounted. Let's think about a workaround, returning `undefined` will probably break a lot of things, but something like `~/absolute/path` or `^/absolute/path` might actually work pretty well.

**Comment by molefrog** [comment]
`../absolute/path` should work as well, but it has some disadvantages imo:
- it's more than just one symbol
- will require some tricky logic to implement properly, `/my/app/` is base, then `/absolute` is `../../absolute`, while `/my/other-app` is `../other-app`.

**Comment by molefrog** [comment]
By the way, it would be also cool to allow `useLocation` to set the absolute path like:
```js
// base is /app, current is /app/home
const [loc, setLoc] = useLocation()
// loc is "/home"

setLoc('~/app2/home')
// loc is "~/app2/home", navigates to "/app2/home"
```

**Comment by jvdsande** [comment]
Hum, right, my bad. I guess my "outofscope" in my actual app _was_ "/", and thus returning the complete path, wielded "/". I should have made more thorough tests!

But this is still confusing. Introducing a modifier to detect whether a path is absolute would indeed be really nice. The added benefit of absolute navigation from inside a nested router is awesome!

**Comment by molefrog** [comment]
Ok, perfect, glad we agreed on the workaround! Feel free to work on the PR, otherwise I could step in and implement it myself.

**Comment by jvdsande** [comment]
I'll see if I find some time to work on it :) would love to participate if I can

**Comment by jvdsande** [comment]
*Resolved by #153 *

**Comment by molefrog** [comment]
Released in https://github.com/molefrog/wouter/tree/v2.7.0

**Comment by jvdsande** [comment]
Perfect thanks!
Sorry I did not have time to test the alpha release, I've updated my app to 2.7.0, everything works just fine now :)
