### ISSUE TITLE
Switch not working properly for Preact

### ISSUE THREAD

**Issue by jvdsande** [molefrog/wouter#155]
Hello, it's me again!

I've recently had to switch from React to Preact, and encountered a problem using `Switch` with Preact.
The issue is due to the way Preact handles its children. If you take the following code:

```js
<Switch>
   {dynamicPages.map((page) => <Route key={page.path} path={page.path}>{page.content}</Route>)}
   <Route path="/:catch*">My Fallback Route</Route>
</Switch>
```

This works fine in React, where the map is spread in the children array, but in Preact this creates a `Switch` with two children: a first children being itself an array, and the catch-all route alone. i.e., Preact does not flatten the children array.

In the `Switch` implementation however, we expect children to either be a single element, or a flattened array. Therefore the array passed as children by Preact will never match the route, we will always see the fallback catch-all route.

I could make a PR to fix this, but I'm wondering what the best way to fix this would be. Basically if we want to fix this, we need to deeply flatten the children array before going through it. Maybe a simple `.flat(Infinity)` would be sufficient, as we should never have cycles there. Or maybe we could implement a recursive way of matching array children.

The main issue I see with this approach, is that is will unnecessarily bloat the React's version as well, which will try flattening an already flattened array.

Is the Preact build of Wouter supposed to be 100% working, or is it maintained as best-effort with React being the main target?

**Comment by molefrog** [comment]
There was another issue #154 regarding how Switch handles its children. It made me wondering if the current way of iterating over children is sufficient. I might need to research the difference of handling `children` prop in React and Preact and get back to you. 

Btw, does the proposed workaround fix the issue:
```jsx
<Switch>
{[
   ...dynamicPages.map((page) => <Route key={page.path} path={page.path}>{page.content}</Route>), 
   <Route path="/:catch*">My Fallback Route</Route>
}]
</Switch>

**Comment by jvdsande** [comment]
Hum, I'd have to test, I'll get back to you tomorrow on that. My guess is that it should indeed work.

Unfortunately my real-life example has multiple static routes next to my dynamic ones so this workaround is not real developer-friendly.

I just saw that Preact exports a `toChildArray` function which handles this flattening. It seems the correct way to go would be to add this function to the react-deps import, and have it being the identity function for the React version. Then in Switch we would just wrap the children definition in this `toChildArray` function. What do you think?

**Comment by molefrog** [comment]
Just made a simple demo, seems like it won't work in React either:
https://codesandbox.io/s/brave-lumiere-rfyh8?file=/src/App.js

I also couldn't find anything regarding the difference in the structure of children [here](https://preactjs.com/guide/v8/differences-to-react), except for [`React.Children`](https://github.com/preactjs/preact-compat/blob/master/src/index.js#L212), but wouter doesn't use that API intentionally to support both React and Preact (otherwise it wouldn't work without `preact-compact`). The only difference afaik is that in Preact `children` is always an array, but there is a line in Switch made specifically for that:
https://github.com/molefrog/wouter/blob/master/index.js#L135

**Comment by jvdsande** [comment]
In my specific case I'm not using Fragments, the dynamic array is _sibling_ to the static routes. It works just fine in React, this is how my app was made.
I've tried adding a `.flat(Infinity)` in the Switch code and it makes it work with Preact.

Using Fragments is indeed another matter. Since the Fragment is the actual child, it seems logical that Routes found inside are _not_ taken into account by the Switch

**Comment by jvdsande** [comment]
Oh - I looked at your demo just now, you're right. Made me check back my app and... My initial version was using React-Router, for which the Switch component works in this case. Changing to Wouter actually broke that but I did not see until making thorough tests for the Preact version.

So that's not a Preact-specific issue after all. I guess I'll change my implementation for an all-dynamic system. Handling this seems to be out of the scope of Wouter, since as you said there is an easy workaround available already :)

**Comment by molefrog** [comment]
> My initial version was using React-Router, for which the Switch component works in this case. 
Yeah, that explains it. React Router's Switch [uses `React.Children.forEach`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Switch.js#L27), which isn't available in Preact. I assume that `forEach` internally unflattens arrays and allows to iterate over nested arrays.

**Comment by jvdsande** [comment]
Let me close this one. Having a single array as children for the Switch will do just fine.
Sorry for taking up your time, I really need to be more thorough in my tests.
