### ISSUE TITLE
Make hooks for params (useParams)

### ISSUE THREAD

**Issue by CoffeJeanCode** [molefrog/wouter#161]
Make a custom hook to use the parameters, to make a better code and have more control of the parameters, and be able to have more flexibility when using them

```jsx
import  useParams  from "wouter/use-params"

const Component = (props) => {
   const parms = useParams( )
  // /user/:name
   return (
     <div>{ params.name  }</div>
  )
} 
```

**Comment by omgovich** [comment]
Hi, @CoffeJeanCode,

`useRoute` doesn't solve the problem?

```jsx
const Component = () => {
  const [, params] = useRoute("/user/:name");
  return <div>{params.name}</hi>
};

```

**Comment by CoffeJeanCode** [comment]
Thanks, you

**Comment by m4n1ac47** [comment]
`useRoute` - doesn't solve the problem because you have to write a full regex in complex-dynamic routes. In a bunch of routes, this becomes a problem. Because it would not be desirable to write it regular expressions in all places.

```js
const Component = () => {
  const [, { id, lang }] = useRoute( '(/)*:lang([a-z]{0,2})/category/([a-z0-9-_]*[-_]*)*:id')
  return <div>{id}</hi>
};
```
