### ISSUE TITLE
README: better documentation on how to use custom components with Links 

### ISSUE THREAD

**Issue by fragsalat** [molefrog/wouter#165]
Hey there,

I've got the issue that onClick isn't fired when I pass a React component as children to Link. Passing a text works.

```
<Link href={`/group/${groupKey}`}>
  <CollapseSeparator key="separator" amount={articles.length - 2} />
</Link>
```

The component is very simple and I used only valid html
```
interface IProps {
  amount: number;
}

export const CollapseSeparator: FC<IProps> = (props) => {
  const { amount } = props;
  return (
    <span className="collapse-separator">
      <span className="amount">{amount}</span>
    </span>
  );
};
```

What have I done wrong?
Thanks upfront

**Comment by molefrog** [comment]
Hi @fragsalat. When using a custom component as a link, you need to make sure your component works well with props that regular `<a />` accepts: `href` and `onClick`. See https://github.com/molefrog/wouter/blob/master/index.js#L121

So in your example, you can fix it by forwarding props to the root element:

```js
export const CollapseSeparator: FC<IProps> = (props) => {
  const { amount, onClick } = props;
  return (
    <span className="collapse-separator" onClick={onClick}>
      <span className="amount">{amount}</span>
    </span>
  );
};
```

I checked the README, it seems like this part was indeed poorly documented. Going to improve the example, thanks!

**Comment by fragsalat** [comment]
Ahh great to know. Would be cool to add this to the examples. Thank you <3

**Comment by molefrog** [comment]
Documented it here:
https://github.com/molefrog/wouter/commit/e1ae11c83c443993066c9f0e0332e7df633fe090
