### ISSUE TITLE
URI with Query Params fails to match

### ISSUE THREAD

**Issue by joe-finreach** [molefrog/wouter#170]
We recently upgraded to 2.7.2, and the pagination for our routes broke. When we tested what had changed, we discovered that when we added a query param to any route, the route was not matched. For example, if we had a route `people/admin` that rendered an Admin panel with a list of people, when we navigated to page two `people/admin?page=2` the default route (404) showed. Downgrading wouter to 2.7.1 solved the problem for us.

**Comment by molefrog** [comment]
Hi @joe-finreach! Thanks for reporting.

Could you share a piece of code that broke in your app?

**Comment by joe-finreach** [comment]
Hi @molefrog I'm happy to share some code. Below is a snippet of (something like) the basic routing we had setup. This code works fine in `2.7.1`, but renders the `ErrorPage` when accessing a URI like `http://www.oursite.com/people?page=2` in `2.7.2`

```javascript
      <Switch>
        <Route path="/people" component={People} />
        <Route path="/courses" component={Courses} />
        <Route path="goals" component={Goals} />
        <Route>
          <ErrorPage code="404" message="Page Not Found" />
        </Route>
      </Switch>
```

**Comment by molefrog** [comment]
Thanks, I think I've spotted the source of the problem already. It's this line:
https://github.com/molefrog/wouter/blob/71ab672cd62af53f396cbd529dfc86ef114f2322/use-location.js#L22

I guess it should be instead:
```js
prevPath.current !== pathname && prevPath.current = pathname && update(currentPathname(base)); 
```

Was recently changed in https://github.com/molefrog/wouter/pull/169

**Comment by molefrog** [comment]
@joe-finreach Fixed in https://github.com/molefrog/wouter/releases/tag/v2.7.3
