### ISSUE TITLE
Using Switch with Router or Scope and Default Routes

### ISSUE THREAD

**Issue by theweiweiway** [molefrog/wouter#175]
Hi!

I'm currently having difficulties using the `Switch` component to default to a Not Found page. My setup:

```
<Switch>
    <Route path="/">HOME</Route>
    <Router base="/auth">
        AUTH ROUTER
        <Route path="/">AUTH HOME</Route>
    </Router>
    <Route>NOT FOUND</Route>
</Switch>
```

`/` takes me to HOME, `/auth` takes me to AUTH ROUTER AUTH HOME, but no matter what I do I cannot get to NOT FOUND. It always goes to AUTH ROUTER without AUTH HOME. 

I also tried replacing `Router` with `Scope` but no luck. It seems like these components work as a Catch-all

I also tried putting my NOT FOUND route into the auth router base, but that doesn't seem to work unless i do `<Route path="/:any*">NOT FOUND</Route>` - and even still that will only match `/auth/:any*`, but not `/authlawjef`

Loving the package though! Super small but does everything I need.

Thanks

**Comment by molefrog** [comment]
@theweiweiway The `Switch` component usually accepts only `Route` components as children, so the easiest way to fix it is to wrap the router in a Route:
```js
<Switch>
  <Route path="/">Home</Route>

  <Route path="/auth/:any*">
    <Router base="/auth">
      <p>Auth Router</p>
      <Route path="/">AUTH HOME</Route>
    </Router>
  </Route>

  <Route>Not found!</Route>
</Switch>
```

However, internally Switch doesn't actually care what type of component you provide to it, the only requirement is that this component should have a valid `path` prop that tells the switch when this segment is active. So you can write just `<Router path="/auth" base="/auth/:any*" />`. And that explains why in your example Router acted as a catch-all component — it didn't have the `path` prop, so switch considered it a default route.

See this sandbox for more details:
https://codesandbox.io/s/wouter-router-in-a-switch-2yxez?file=/src/index.js

**Comment by theweiweiway** [comment]
Ah, got it. Thanks!
