### ISSUE TITLE
View doesn't sync with url on IE11

### ISSUE THREAD

**Issue by OshotOkill** [molefrog/wouter#179]
I'm doing IE11 compatible tests and find out an issue that view/component doesn't change when I click a route while the url has already changed.

I inspect the code and have come to the conclusion that it's the problem in `/use-location.js`:

https://github.com/molefrog/wouter/blob/a7f09709bc1c3cf2b423bd2a69a1efec8845835d/use-location.js#L70

According to MDN, IE doesn't support `Event Constructor` feature, 

<img width="1052" alt="截屏2021-03-02 下午5 05 51" src="https://user-images.githubusercontent.com/6079112/109624810-966e4380-7b79-11eb-9f38-fc937848a241.png">

so I import a polyfill [`new-event-polyfill`](https://github.com/RaphaelHaettich/new-event-polyfill) and everything works properly.

I suppose we should ship such polyfill with library or tell users to download a `Event Constructor` polyfill by themself.

**Comment by molefrog** [comment]
Hey @OshotOkill, thanks for researching this out! I can confirm that `Event` is a platform API, and hence isn't included in core-js and needs to be polyfilled manually. I don't think we should ship it with the library, but I'm going to make sure it's mentioned in the README. Thanks!

**Comment by molefrog** [comment]
Done via #181
