### ISSUE TITLE
Redirect based on Cookie is laggy on production

### ISSUE THREAD

**Issue by amiregelz** [molefrog/wouter#187]
My App.js looks like this:

```
<Route path="/onboarding"><Onboarding /></Route>
<Route path="/dashboard"><Console /></Route>
{Cookies.get('token') ? <Redirect to='/dashboard' /> : <Redirect to='/onboarding' />}
```

When I debug locally, it works fine.
On production, when the cookie doesn't exist, it redirects to the dashboard for a split second and then redirects to the correct route (the onboarding).

I'm using js-cookie to read and write cookies.
Am I missing something?

**Comment by molefrog** [comment]
Hi, @amiregelz! I would suggest using declarative `<Redirect />`  components only when the structure is known at the compile time. The reason is that these components have a strong side effect — they change the location once rendered. 

You can rewrite your code with hooks:

```js
import { useLocation } from "wouter"
import { useEffect } from "react"

const App = () => {
  const [location, setLocation] = useLocation()
  
  useEffect(() => {
    if (Cookies.get('token')) {
      setLocation('/dashboard);
    } else {
      setLocation('/onboarding');
    }
  }, []) 

  return (
    <>
      <Route path="/onboarding"><Onboarding /></Route>
      <Route path="/dashboard"><Console /></Route>
    </>  
  )
}

```

**Comment by amiregelz** [comment]
Thanks a lot, solved my issue :)
