### ISSUE TITLE
There's a way to redirect and prevent go back in route history ?

### ISSUE THREAD

**Issue by lucas-santosP** [molefrog/wouter#188]
For example, after doing logout clear the go back routes in the browser. I was trying to achieve this using the replace option on setLocation method from useLocation but didn't seem to change anything.

`
setLocation("/login", { replace: true })
`

I know that is possible to prevent access to an unauthorized route with other ways like checking if the user is authorized before mounting the component and etc...
But I would like to know what is the expected behavior of passing the replace option in the setLocation method ? And it's possible to clear the user history ?

**Comment by molefrog** [comment]
`setLocation("/login", { replace: true })` is identical to calling `location.replaceState(..)` and it should replace the current address with the new one. 

>  but didn't seem to change anything
Could you clarify what exactly didn't work? Did the URL in the address bar change?

> And it's possible to clear the user history ?
Not possible. You can only replace the current address with the new one, but you can't modify the history.

**Comment by lucas-santosP** [comment]
> Could you clarify what exactly didn't work? Did the URL in the address bar change?

The URL changed. When I said "didn't seem to change anything" I mean when compared to not passing the replace option as true, that's why a asked what is the difference between them.

> is identical to calling `location.replaceState(..)`

Ok, so without the replace option would be equivalent to the call `location.pushState` ?

**Comment by molefrog** [comment]
> Ok, so without the replace option would be equivalent to the call `location.pushState` ?
Correct! It creates a new history entry.

**Comment by lucas-santosP** [comment]
Ok, thanks for answering and for the awesome lib.
