### ISSUE TITLE
resetScroll on routes changes

### ISSUE THREAD

**Issue by bermudezjorge** [molefrog/wouter#189]
I really like wouter is small and has everything I need, but I was facing a problem that the scroll doesn't reset on routes changes. Would be a nice idea we can set a prop to reset scroll on routes changes.

**Comment by vially** [comment]
This seems to be already possible using the solution suggested here: https://github.com/molefrog/wouter/issues/132#issuecomment-704372204.

**Comment by molefrog** [comment]
I agree with @vially, the solution proposed in react-router docs should work just fine. 
By the way, they also have an nice explanation of why this feature is no longer the part of the library and I think we should follow the same approach here.

https://reactrouter.com/web/guides/scroll-restoration
