### ISSUE TITLE
Special characters in URL result in 404

### ISSUE THREAD

**Issue by jeerbl** [molefrog/wouter#190]
Hi and thank you for the work on this router, it's been great to use so far!

I'm having an issue though where, when the URL contains a dot (say `/fund/BTCC.B`), my route `/fund/:param` is not triggered, resulting in a 404. Is there a solution around this?

Thanks!
Jerome

**Comment by cbbfcd** [comment]
@jeerbl i create a simple demo [here](https://codesandbox.io/s/wouter-react-forked-8ryjn?file=/src/index.js), it works well, is there anything i ignored?

**Comment by molefrog** [comment]
Hey @jeerbl can you check the demo provided by @cbbfcd solves the issue?

**Comment by jeerbl** [comment]
It did! Sorry meant to send a message earlier.
