### ISSUE TITLE
Error: null in setLocation()

### ISSUE THREAD

**Issue by Yoshiki-Iwasa** [molefrog/wouter#195]
Hello! Now, I'm in trouble with a strange error of setLocation ><

I'm using `useLocation` and 'setLocation' like the following code.

component.tsx
```typescript
const Component: React.FC = () => {
	const [location, setLocation] = useLocation();
	const [match, params] = useRoute(
	  "/somewhere"
	);
	//////

	function onSubmitHandler() {
	  async function getInfo() {
		
		try {
		  const resp = await fetch("url")
		  const data = (await resp.json()) as Object;
		  if (data == null) {
			alert("error");
		  }
		  console.log(data);
		  setLocation(`/url/${data.name}`);
		} catch (e) {
		  console.log(e);
		  return;
		}
	  }
	  try {
		getInfo();
	  } catch (e) {
		return;
	  }
	}

	return (
		<div>
			<Button onClick={onSubmitHandler}>
			</Button>
		</div>
	);
  };
  
```

But SOMETIMES `setLocation(`/url/${data.name}`);` cause an Error.
<img width="1120" alt="スクリーンショット 2021-05-22 16 23 57" src="https://user-images.githubusercontent.com/58158284/119218209-36ed5780-bb1a-11eb-87c6-d2664fd5c709.png">

I don't know how to procedure for reproducing this Error. This happens sometimes but happens actually (TT)
Is my usage collect? What do you guess causes this issue ?

**Comment by molefrog** [comment]
It's hard to tell what exactly causes that, here is a list of things I would try to dig into:
1. You are using an async/await function inside a component and it could be possible that by the time request promise resolves, your component has already left the tree. You then call `setLocation` and it tries to modify local state of the component on an unmounted node. See https://dev.to/pallymore/clean-up-async-requests-in-useeffect-hooks-90h for more info on that.
2. I would try wrapping the `onSubmitHandler` with `useCallback` and providing the full list of dependencies used `useCallback(..., [setLocation])` to exclude the possibility of having stale `setLocation`.

Also, could you make a simple CodeSandbox demo?

**Comment by molefrog** [comment]
Is this still relevant? I'm going to close this issue, feel free to reopen if the error still occurs.
