### ISSUE TITLE
Feature: animation support. 

### ISSUE THREAD

**Issue by cbbfcd** [molefrog/wouter#197]
I was wondering if I could provide support for route switching animation, this is an interesting feature. 😄

**Comment by molefrog** [comment]
Sound nice, what do you have in mind?

**Comment by cbbfcd** [comment]
Users can use third-party animation libraries to achieve perfect animation support, while `wouter` only needs to provide subtle support or nothing.

I implemented animation support in two ways:

1. use [react-transition-group](https://github.com/reactjs/react-transition-group)

[here is a simple animation support implementation](https://codesandbox.io/s/wouterwith-react-transition-group-8ryjn?file=/src/index.js:233-255)

Almost directly used to achieve the goal！

In order to control the entry and exit animation in more detail, whether to consider providing state.action:'PUSH' or'POP' for users？just like `react-router`.

2. Customize Route Switch with animation function

[here is a simple animation support implementation](https://codesandbox.io/s/wouter-animations-custom-activeswitch-z7d01?file=/src/index.js)

use `react-motion`, wo can make a AnimateRoute and AnimateSwitch

so, 

Whether wouter should have built-in support for animation, my understanding is that it is not needed. This part of the task seems to be implemented by the user without too much code.
All we need to do is add the demo link in the readme.

**Comment by molefrog** [comment]
Thanks for the demos, they look neat! Could you provide an example, not sure what you meant here:

> // wouter should provide a ACTION like 'react-router'?
> // so user can fully contorl the enter and exit animation.

**Comment by molefrog** [comment]
In general, wouter (as well as react-router) is designed to be decoupled from tasks like animations, since it is basically just conditional view rendering. As long as you can animate a view transition that doesn't depend on current location (e.g. [tabs](https://jeetiss.github.io/tabs/) in your app, you can definitely achieve that with wouter. 

The `AnimatedSwitch` code does indeed look a bit complex, is there any way we can simplify that?

**Comment by cbbfcd** [comment]
> Could you provide an example, not sure what you meant here

The css animation here needs to provide an entry class and an entry class. I have checked some cases and judged by the type of action type `PUSH` `POP` `REPLACE`. However, this is not something we should care about. I have Deleted related notes.

> The AnimatedSwitch code does indeed look a bit complex, is there any way we can simplify that?

I made a small modification based on [react-router-transition](https://github.com/maisano/react-router-transition), just to illustrate that users can make their own routing animation tools based on the methods exposed by `wouter` combined with the excellent animation engines of the community,

if necessary, I can improve this and make a `@wouter/animate`?

so, we can:

```js
import { AnimateSwitch } from '@wouter/animate'
```

**Comment by molefrog** [comment]
Hi @cbbfcd, sorry that it took me so long to reply. Is this still relevant?
Btw, the namespace `@wouter` is occupied on npm 😢

**Comment by cbbfcd** [comment]
Sorry, it's been too long, I need to rethink and reorganize the code. @molefrog

**Comment by molefrog** [comment]
Hi @cbbfcd, I hope you don't mind if I close this issue. We're actively working on the next major release right now (`v3` branch), and this won't be our focus in the nearest future. However, once the release is out, I think we can rethink how animations are going to be supported natively.
