### ISSUE TITLE
Nested routes with hash navigation

### ISSUE THREAD

**Issue by evenfrost** [molefrog/wouter#198]
Is there an example of how to make nested routes with hash-based navigation? Sorry in advance for this being more like a question, though I didn't manage to make it work when combining hash and nested examples from the readme.

**Comment by cbbfcd** [comment]
[demo](https://codesandbox.io/s/wouter-demo-nested-routes-forked-3n1ng?file=/src/index.js)

Now you can refer to this example first, there is a problem with getting the base path when nesting, I will raise a PR to make the work less cumbersome
