### ISSUE TITLE
Feature: Switch / Pattern Matcher Hook

### ISSUE THREAD

**Issue by ryanking1809** [molefrog/wouter#199]
I'm finding it useful to have a `useSwitch` hook - it allows me to do things like authorization in the parent component rather than repeating it inside each route. It's like a `useRoute` for when you don't know which pattern to expect. I've thrown together my own hook but thought I would propose it as a feature in case you think others would find it useful. 

```js
const Page = () => {
    // if location = "/projects/123", useSwitch will return ["/projects/:id", { id: 123 }]
    const [pattern, params] = useSwitch(["/dashboard", "/projects/:id", "/user/:id"]);
    if (!hasPermissions(pattern, params)) {
        return <NotAuthorizedPage />
    }
    return getPage(pattern, params);
}
```

```js
const useSwitch = (patterns = []) => {
	const [location] = useLocation();
	const { matcher } = useRouter();
	let matchedPattern = [];
	patterns.find((p) => {
		const [match, params] = matcher(p, location);
		if (match) {
			matchedPattern = [p, params];
		}
		return match;
	});
	return matchedPattern;
};
```

**Comment by cbbfcd** [comment]
You mean built in wouter?

**Comment by ryanking1809** [comment]
Yeah, the way I see it is `<Router>`, `<Route>`, `<Link>`, and `<Redirect>` all have hook equivalents -  but `<Switch>` does not. But I just saw molefrog wouldn't like to expand the feature set much (https://github.com/molefrog/wouter/issues/108) so maybe I'll close this one - not a big deal :)
