### ISSUE TITLE
How to add an 404 route?

### ISSUE THREAD

**Issue by wansaleh** [molefrog/wouter#20]
Hello. Nice routing library you got here. But I can't find a way to do a "default route" eg to create a 404 error route.

Can you shed some info on this?

Thanks.

**Comment by molefrog** [comment]
@wansaleh Hi! Thanks 😊 
I put together a small demo that illustrates the use case: https://github.com/molefrog/wouter/blob/master/README.md#a-default-route

Hope this helps! Closing this as a dup of https://github.com/molefrog/wouter/issues/16

**Comment by molefrog** [comment]
The `Switch` component isn't documented in the README and that's something I'm planning to work on soon.

**Comment by wansaleh** [comment]
Thank you so much @molefrog !!
