### ISSUE TITLE
Not Found route always shown

### ISSUE THREAD

**Issue by stefensuhat** [molefrog/wouter#201]
Hi I've this code:

```
//Route.js

<NestedRoutes base="/logs">
      <Route>
        <LogsMainPage updateQuery={setQuery} />
      </Route>
      <Route
        path="/logs/detail"
        component={props => {
          return React.createElement(LogDetailsPage, {
            currentMainPageQuery: query,
            ...props,
          });
        }}
      />
      <Route
          path={'/:rest*'}
          component={params => <h1>Not Found {params.rest}</h1>}
        />
    </NestedRoutes>
```
```
// NestedRoutes.js
const NestedRoutes = props => {
  const router = useRouter();
  const [parentLocation] = useLocation();

  const nestedBase = `${router.base}${props.base}`;

  // don't render anything outside of the scope
  if (!parentLocation.startsWith(nestedBase)) return null;

  // we need key to make sure the router will remount when base changed
  return (
    <Router base={nestedBase} key={nestedBase}>
      {props.children}
    </Router>
  );
};
```

The problem is everytime the page render it always shown `Not Found` (main content is rendered ie: LogsMainPage) even though the url is correct. Tried digging but can't found how to fix this "not found" url. Is there any guide to set this up properly?

----
I've edit the example from docs on the "help center routing" I put the same code to show Not Found

https://codesandbox.io/s/wouter-demo-nested-routes-forked-qmg6q

**Comment by molefrog** [comment]
Hi, I think you need to wrap your routes with a switch. I forked your sandbox, please check if it solved the problem:

https://codesandbox.io/s/wouter-demo-nested-routes-forked-j3tfn?file=/src/index.js

**Comment by stefensuhat** [comment]
this fixed the issue. sometimes I struggle to used setLocation.
