### ISSUE TITLE
Add "Default Redirect" to FAQ?

### ISSUE THREAD

**Issue by Obiwarn** [molefrog/wouter#203]
This is probably super simple, but I have a hard time to redirect the user to a default page when he enters the root url:

e.g. auto redirect

`www.foo.com`

to

`www.foo.com/todos`

I tried sth. like this

```
  const [location, setLocation] = useLocation();
  if (location === "/") {
    setLocation("/todo");
  }
```

**Comment by molefrog** [comment]
Hi, I guess the reason is that you can't use imperative code (that mutates state, or does any side-effects) in a component's render function. I recommend taking a look at `useEffect` hook:

```js
  const [location, setLocation] = useLocation();

  useEffect(() => {
    if (location === "/") setLocation("/todo");
  }, [location])
```

**Comment by molefrog** [comment]
@Obiwarn Did it help to solve your problem? let me know if you need more help with that and feel free to reopen.

**Comment by Obiwarn** [comment]
Sorry for answering so late. 

It was an error deep down in my code, unrelated to Wouter, causing an infinite loop on second reload.

Both versions above work just fine (but one should use `useEffect` here as you suggested).
