### ISSUE TITLE
License

### ISSUE THREAD

**Issue by TheoBr** [molefrog/wouter#205]
Heyo!

Was wondering if there's any particular reason why wouter is distributed without a license. Would be nice to have an MIT or similar thrown on it to be able to ship with confidence :)

**Comment by molefrog** [comment]
Hi, @TheoBr, wouter is licensed [with the ISC](https://github.com/molefrog/wouter/blob/master/package.json#L56). I made a decision to ship it without a LICENSE.md file, since specifying it in package.json should legally be enough.

Though we could add a short section to the README.

**Comment by molefrog** [comment]
Just to make sure I checked the npmjs.org and it picks up the license properly: https://www.npmjs.com/package/wouter

**Comment by TheoBr** [comment]
My bad - ty!
