### ISSUE TITLE
Typescript route path

### ISSUE THREAD

**Issue by kimmikirino** [molefrog/wouter#207]
Hi,

I am trying to create a multipath routes using typescript, but when I use the structure mentioned in the docs, I'm getting an error for the path type

![image](https://user-images.githubusercontent.com/29700468/130282223-92e4df26-d1dd-4dd3-8b53-434220c3c676.png)

code:

```
import makeMatcher from "wouter/matcher";

const defaultMatcher = makeMatcher();

/*
 * A custom routing matcher function that supports multipath routes
 */
const multipathMatcher = (patterns, path) => {
  for (let pattern of [patterns].flat()) {
    const [match, params] = defaultMatcher(pattern, path);
    if (match) return [match, params];
  }

  return [false, null];
};

const App = () => (
  <Router matcher={multipathMatcher}>
    <Route path={["/app", "/home"]}>...</Route>
  </Router>
);
```

Am I missing something?
thanks in advance.

**Comment by cbbfcd** [comment]
hi, type declaration of `Route` component:

```js
export interface RouteProps<T extends DefaultParams = DefaultParams> {
  children?: ((params: Params<T>) => ReactNode) | ReactNode;
  path?: Path;
  component?: ComponentType<RouteComponentProps<T>>;
}
```

about the `Path`:

```js
export type Path = string;
```

so, i think you can make a custom `Route` component to resolve this problem:

```ts
import { useRoute } from "wouter"
const  MultipathRoute = ({ paths, match, component, children }) => {
  const useRouteMatch = useRoute(paths);
  // ...
}
```

hope it's useful.

**Comment by kimmikirino** [comment]
@cbbfcd Hi,
thank you for responding. 
It is a good idea, but `useRoute` receives a `Path` type too.

**Comment by cbbfcd** [comment]
Hi, here are some workrounds I thought of:

1. keep the path as `string`, use a special separator what you like to split the path string

```js
<Route path='/foo&/bar'/>
``` 
then you can split it in your custom matcher, I did not actually run it, but it should be feasible.

2. custom your own `Route`

```js
import { useLocation } from "wouter"
export const MultipathRoute = ({ path, match, component, children }) => {
  const useRouteMatch = yourMatchrt(path, useLocation()[0]);
  // ...
};
```
3. override the type declaration

**Comment by kimmikirino** [comment]
Got it, gonna try like that : )

thank you for your help
