### ISSUE TITLE
Can wouter be used with NextJS?

### ISSUE THREAD

**Issue by carlosagsmendes** [molefrog/wouter#222]
Hi,

I'm trying to use wouter with NextJS.

The staticLocationHook returns a function so I can't serialize it and pass it as a prop using the provided code:

```
 const prerendered = renderToString(
    <Router hook={staticLocationHook(req.path)}>
      <App />
    </Router>
  );
```

Any suggestions?

Thanks in advance!

**Comment by cbbfcd** [comment]
Hi, could you provide an example, not sure what you meant here:?

> I can't serialize it and pass it as a prop

**Comment by carlosagsmendes** [comment]
@cbbfcd sure, when I try to use wouter with a NextJS server side page I get the following error that you can see live on [this codesandbox](https://codesandbox.io/s/async-night-phm9i?file=/pages/index.js)

![image](https://user-images.githubusercontent.com/1224078/139963706-0b95da8e-9384-4613-b63b-adfcf2377bc0.png)

My understanding is that I'm getting this error since I'm rendering the page server side. From [wouter's ssr documentation](https://github.com/molefrog/wouter#is-there-any-support-for-server-side-rendering-ssr) since I'm using SSR I need to use the _staticLocationHook_ server-side and pass it to the Router.

My issue is that when I try to pass the hook as a prop in NextJS I get the following error:

```
error - Error: Error serializing `.wouterHook` returned from `getServerSideProps` in "/".
Reason: `function` cannot be serialized as JSON. Please only return JSON serializable data types.
```
You can see the error in the [codesandbox](https://codesandbox.io/s/async-night-phm9i?file=/pages/index.js) by uncommenting line 17

![image](https://user-images.githubusercontent.com/1224078/139964820-a2c5f69d-2190-484f-9e5e-333f7b60a327.png)

Thanks in advance!

**Comment by cbbfcd** [comment]
hi, @carlosagsmendes 
thanks for the demo provided, I am not very good at `nextjs`, i checked the [relevant documents](https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering) and found this limitation:

> getServerSideProps should return an object with:

> props - An optional object with the props that will be received by the page component. It should be a serializable object or a Promise that resolves to a `serializable object`.

but the `staticLocationHook` will return a `function` which can not be serialized.

so, i think, maybe we can pass an `url` string to component ?:

```js
export async function getServerSideProps(context) {
  let res = await fetch("https://pokeapi.co/api/v2/pokemon?limit=500");
  let results = await res.json();
  // const hook = staticLocationHook(context.req.url);

  // maybe should pass the url to the component?
  const url = context.req.url;

  return {
    props: {
      data: results,
      url
      // wouterHook: hook
    }
  };
}
```

i forked your demo and run success, just [here](https://codesandbox.io/s/happy-cherry-wkfz6?file=/pages/index.js:238-626)

**Comment by carlosagsmendes** [comment]
Thank you ever so much @cbbfcd 

I don't get any error, but when I click on the links (i.e.: Home, For Sale, Sold Items, FAQ) the Routes are not being loaded. Any idea on what I may be missing?

**Comment by cbbfcd** [comment]
The `staticLocationHook` function creates a hook that always responds with a path provided, so

> Make sure you replace the static hook with the real one when you hydrate your app on a client.

> If you want to be able to detect redirects you can provide the record option:

```js
import { renderToString } from "react-dom/server";
import { Router } from "wouter";
import staticLocationHook from "wouter/static-location";

import App from "./app";

const handleRequest = (req, res) => {
  const location = staticLocationHook(req.path, { record: true });
  const prerendered = renderToString(
    <Router hook={location}>
      <App />
    </Router>
  );

  // location.history is an array matching the history a
  // user's browser would capture after loading the page

  const finalPage = locationHook.history.slice(-1)[0];
  if (finalPage !== req.path) {
    // perform redirect
  }
};
```

**Comment by carlosagsmendes** [comment]
Thanks again @cbbfcd!

Could you please clarify what you mean by  "replace the static hook with the real one when you hydrate your app on a client."?

This was what I tried to do but it doesn't make any difference. The links still don't navigate. 

![image](https://user-images.githubusercontent.com/1224078/140049375-bad8d939-8417-4ea1-b211-3f3248a767de.png)


[Here's an updated codesandbox](https://codesandbox.io/s/silly-lovelace-n1mc1?file=/components/wouterApp.js) in case you want to take a look.

**Comment by cbbfcd** [comment]
In the rehydration process, replace with the default `hook` of `wouter`. The more extreme method is to judge the `window` when returning, and then return to the page, so that the front-end routing is used.

[your demo](https://codesandbox.io/s/wonderful-orla-0zppo?file=/components/wouterApp.js)

**Comment by carlosagsmendes** [comment]
Thanks again! 

I will close the issue and try to come up with examples for both cases in case someone else wants to use it!

Could you just please clarify what you mean by "originalLocationHook"?

_//hook={typeof window === 'undefined' ? hook : originalLocationHook}_

**Comment by cbbfcd** [comment]
> Thanks again!
> 
> I will close the issue and try to come up with examples for both cases in case someone else wants to use it!
> 
> Could you just please clarify what you mean by "originalLocationHook"?
> 
> _//hook={typeof window === 'undefined' ? hook : originalLocationHook}_

here 😄：

```js
import originalLocationHook from "wouter/use-location";
```

**Comment by carlosagsmendes** [comment]
Many thanks for all the help!
