### ISSUE TITLE
How to create a private Route with Wouter?

### ISSUE THREAD

**Issue by Sotatek-PhuongNguyen4** [molefrog/wouter#223]
I want to create a private route like react-router-dom like this code: But I's not the same with Wouter. Route (Wouter) does'nt have render property. What is the replacement in Wouter?

`export const PrivateRoute = ({component : Component, ...rest}) => (
    <Route
        {...rest}
        render = {
            props => (
                localStorage.getItem("token")
                ? <Component {...props} /> 
                : <Redirect to="/login" />
            )
        }
    />
);`

**Comment by cbbfcd** [comment]
hi, 

`wouter` does not have a `render` attribute, but it also supports `render children` or `custom component`. The code is here:

```js
export const Route = ({ path, match, component, children }) => {
  const useRouteMatch = useRoute(path);

  // `props.match` is present - Route is controlled by the Switch
  const [matches, params] = match || useRouteMatch;

  if (!matches) return null;

  // React-Router style `component` prop  @Sotatek-PhuongNguyen4 👀 👇
  if (component) return h(component, { params });

  // support render prop or plain children @Sotatek-PhuongNguyen4 👀 👇
  return typeof children === "function" ? children(params) : children;
};
```

`wouter` is based on `hooks`, which is more flexible to a certain extent. You can achieve your goals in many ways:

1. custom your `Route` component:
```js
export function YourPrivateRoute (props) {
  const renderChildren = () => localStorage.getItem("token") ? <Component {...props} /> : <Redirect to="/login" />;
  return (
    <Route>{renderChildren}</Route>
  )
}
```

2. custom your `usePrivateLocation` hook
```js
// ... 
// refer https://github.com/molefrog/wouter/blob/master/use-location.js
const navigate = useCallback(
    (to, { replace = false } = {}) =>
        history[replace ? eventReplaceState : eventPushState](
        null,
        "",
        // handle nested routers and absolute paths
        localStorage.getItem("token") ? (to[0] === "~" ? to.slice(1) : base + to) : "/login"
     ),
    [base]
  );
```
These are some of the solutions that I temporarily thought of. although they may not be the best solution, they can solve your problem and are enough to illustrate the flexibility and scalability of `wouter`.

**Comment by Sotatek-PhuongNguyen4** [comment]
hi @cbbfcd
Thank you so much for your answer. It's really helpful for my technique. My problem was resolved clearly. <3
