### ISSUE TITLE
How to go to previous page?

### ISSUE THREAD

**Issue by Sotatek-PhuongNguyen4** [molefrog/wouter#234]
I want to go to previous page using wouter without using window.history.back() ?
Thanks you so much for helping me with this issue.

**Comment by cbbfcd** [comment]
you can custom your own `useLocation` hook, like [this file](https://github.com/molefrog/wouter/blob/master/use-location.js), and you can get the `prev hash string`, so you can custom a function like `goBack`, to navigate to prev hash router.
