### ISSUE TITLE
How to make a Router with dynamic base

### ISSUE THREAD

**Issue by Sotatek-PhuongNguyen4** [molefrog/wouter#235]
I want to have Router component with dynamic base like:

        <Router
               base="/assets/:id1/:id2"
         ><Router>

 
 I handled this issue by using state to manage base props like the below code:

        const Routes = () => {
            const [firstMatchRoute, setFirsttMatchRoute] = useState('')
            const [sencondMatchRoute, setSecondMatchRoute] = useState('')
        
            const [location] = useLocation()
        
            useEffect(() => {
                const parsedData = location.split('/')
                setFirsttMatchRoute(parsedData[2])
                setSecondMatchRoute(parsedData[3])
            })
        
            return (
                <Suspense fallback={false}>
                    // Custom nested router
                    <NestedRoutes
                        base={'/assets/' + firstMatchRoute + '/' + sencondMatchRoute}
                        component={() => <LazyComponent component="Detail" />}
                    />
                </Suspense>
            )
        }

This solution generates unnecessary renders for Detail component. So I don't want to do this.

**Comment by cbbfcd** [comment]
if just want to get the matched params, you can try:
```js
useRouter().matcher(pattern, path)
```

**Comment by Sotatek-PhuongNguyen4** [comment]
@cbbfcd  no. I just want to make the base route of Router dynamic with the same page. 
Example:
  localhost:3000/abcd/history
  localhost:3000/efgh/history 
Two routes render same page, but the base is different (abcd and efgh)

**Comment by cbbfcd** [comment]
@Sotatek-PhuongNguyen4 
i found a workaround, just custom your own `use-location` hook, focus on [`here`](https://github1s.com/molefrog/wouter/blob/HEAD/use-location.js#L85-L86)

**Comment by molefrog** [comment]
Closing this, as it seems to be resolved.

**Comment by Bonfims** [comment]
hey, its not clean to me, i want to use Router with a base path like "base={/:template}" to use "template" value, but doent work, i need to do to every template i have like routes with "base={/users}", "base={/files}" and "base={/posts}" :(

**Comment by Bonfims** [comment]
Sorry guys, i endeed up with: 

```
<Route path="/:template/:any*">
    {({template}) => <NestedRouter base={`/${template}`}>
	    <Switch>
		    <Route path="/:document">
			    <Document />
		    </Route>
		    <Route>
			    <List />
		    </Route>
	    </Switch>
    </NestedRouter>}
</Route>
```
I using a "Route" to get parameter with "/:template" and passing it down to a "NestedRouter" and setting "base" with their value, and activing a Router with dynamic base.

**Comment by molefrog** [comment]
> Sorry guys, i endeed up with:
> 
> ```
> <Route path="/:template/:any*">
>     {({template}) => <NestedRouter base={`/${template}`}>
> 	    <Switch>
> 		    <Route path="/:document">
> 			    <Document />
> 		    </Route>
> 		    <Route>
> 			    <List />
> 		    </Route>
> 	    </Switch>
>     </NestedRouter>}
> </Route>
> ```
> 
> I using a "Route" to get parameter with "/:template" and passing it down to a "NestedRouter" and setting "base" with their value, and activing a Router with dynamic base.

Right, it does not look appealing I know, but fortunately we are working on the next big release that will bring the native support for nested routes (with dynamic base!). You can track the progress here https://github.com/molefrog/wouter/pull/356

Stay tuned for the updates.
