### ISSUE TITLE
Prevent navigation on Link component if event was cancelled

### ISSUE THREAD

**Issue by Tomas2D** [molefrog/wouter#237]
Due to calling `onEvent` (passed from props) after doing navigation, one cannot prevent cancelling the navigation process.

I propose to call `onClick` before `navRef.current();` and then check if event was cancelled via `e.isDefaultPrevented()`. If so, then do not call `navRef.current()` action. What do you think?

https://github.com/molefrog/wouter/blob/cba34af73d01389be18d0ed275611336946c18fe/index.js#L98-L118

**Comment by Tomas2D** [comment]
I able to make a PR if you do not have a time, that is not a problem. @molefrog

**Comment by molefrog** [comment]
That would make a lot of sense, is `event.isDefaultPrevented` part of the web standard? To my shame, I haven't used this method. 

Also, PRs are highly welcomed!

**Comment by Tomas2D** [comment]
It looks like that `defaultPrevented` property is, also with high [browser compatibility](https://developer.mozilla.org/en-US/docs/Web/API/Event/defaultPrevented#browser_compatibility) as can be seen here. 

This simple [https://codesandbox.io/s/divine-bash-lhoxd7?file=/src/App.js](codesandbox) demonstrate the funcionality.

I will create an PR.

**Comment by molefrog** [comment]
Landed in https://github.com/molefrog/wouter/releases/tag/v2.8.0 🎊
