### ISSUE TITLE
[feature] wouter v3 will coming soon?

### ISSUE THREAD

**Issue by cbbfcd** [molefrog/wouter#238]
wondering what kind of feature drives everyone crazy? 😂

**Comment by molefrog** [comment]
Hi all, Alexey is here. I hate to ignore all of the messages, I've seen some increasing interest for wouter lately. I've got some personal stuff I'm currently dealing with. But I hope to get back soon and clear the backlog, so we can release the new version soon.

**Comment by molefrog** [comment]
I've started making some notes on what could be included in v3. I'll put together a document, but here are some initial ideas:
- Support React 18, `useSyncExternalStore` etc.
- Better design of nested routes and probably making `Router` just a wrapper around a route. This will allow us to introduce `useParams`
- Drop support for TS < 4 maybe?
