### ISSUE TITLE
called twice useEffect in StrictMode.

### ISSUE THREAD

**Issue by shiyiya** [molefrog/wouter#241]
![image](https://user-images.githubusercontent.com/34017352/162373587-8dc01c1d-a467-4e73-bc24-d28d1e7d2911.png)

![image](https://user-images.githubusercontent.com/34017352/162373491-698b4c67-5bbc-4239-b3fe-8561411d57e2.png)

**Comment by Gounlaf** [comment]
https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects

> Strict mode can’t automatically detect side effects for you, but it can help you spot them by making them a little more deterministic. This is done by intentionally double-invoking the following functions:
> 
> * Class component constructor, render, and shouldComponentUpdate methods
> * Class component static getDerivedStateFromProps method
> * Function component bodies
> * State updater functions (the first argument to setState)
> * Functions passed to useState, useMemo, or useReducer
> 
> > Note:
> > This only applies to development mode. Lifecycles will not be double-invoked in production mode.

**Comment by shiyiya** [comment]
as design. 
https://reactjs.org/blog/2022/03/29/react-v18.html#new-strict-mode-behaviors
