### ISSUE TITLE
[question] Custom useState Router hook returns different state

### ISSUE THREAD

**Issue by amorawski** [molefrog/wouter#243]
Hi, I am working on a react-native application (for sake of development also using react-native-web). I would like to use a simple Router hook based on the useState. It looks like what is returned from useLocation differs from what I get via useRouter.hook. It feels like each time the useRouter is called different state is being used. Could you please help me clarify if this is a bug or I'm just doing someting really bad here (**"wouter": "^2.8.0-alpha.2"**). Thanks. Simple demo:

```javascript

const useHook = ({ base } = {}) => {
  return useState(base);
}

function Inner() {
  const [location, setLocation] = useLocation();

  const router = useRouter();
  const [badLocation] = router.hook(router);

  console.log("Am I sad?", location !== badLocation);

  return (
    <View>
      <Route path='one'>
        <Pressable onPress={() => setLocation('two')}>
          <Text>Go to two</Text>
        </Pressable>
      </Route>
      <Route path='two'>
        <Pressable onPress={() => setLocation('one')}>
          <Text>Go to one</Text>
        </Pressable>
      </Route>
    </View>
  )
}

export default function App() {
  return (
    <View>
      <Router hook={useHook} base={'one'}>
        <Inner/>
      </Router>
    </View>
  )
}
```

**Comment by cbbfcd** [comment]
haha~, can produce a codesandbox demo?

**Comment by amorawski** [comment]
https://codesandbox.io/s/throbbing-cookies-n4dvt6?file=/App.js

**Comment by HelKyle** [comment]
> [codesandbox.io/s/throbbing-cookies-n4dvt6?file=/App.js](https://codesandbox.io/s/throbbing-cookies-n4dvt6?file=/App.js)

Cause your `useHook` doesn't sync from something like location, so it's two hooks with different state

```

const useHook = ({ base } = {}) => {
  return useState(base);
};

function Inner() {
  const [location, setLocation] = useLocation();

  const router = useRouter();
  // equals to const [badLocation] = useHook(router);
  // it's a new useState hook right?
  const [badLocation] = router.hook(router);
}
```

**Comment by amorawski** [comment]
Thank you for your quick reply.

I thought that this line `<Router hook={useHook} base={'one'}>` is meant to force both `router.hook` and `useLocation` to use exactly the same state. So that somewhere behind the scenes my `useHook` is called and mentioned calls are operating on the same state (which could be later on updated via `setLocation` or `setBadLocation` which would invoke my `setHook`). As I understood it, the `hook` property was assigned to the overlapping Router, so the state returned should also be singular (related to the overlapping Router), no matter how I access it (either via `router.hook` or `useLocation`).

To make the above work, should I extract the `useState` from the `useHook` or is there a better solution? Or maybe what I'm trying to achieve is simply against the design?

**Comment by HelKyle** [comment]
The core point is every time you call a useState hook, it's a completely new one with independent state~ So in the view of react, your Inner function looks as follow.

```js
function Inner() {
  const router = useRouter();
  const [location, setLocation] = useState(router);

  const [badLocation] = useState(router);
}
```

When you run `setLocation`, of course the second one will not change, they are difference state from two hooks.

**Comment by HelKyle** [comment]
To sync state from hooks, you can change useHook like this~(only for demo)

```js
const useHookEvent = "$$useHookEvent";
const useHook = ({ base } = {}) => {
  const [state, setState] = useState(base);
  useEffect(() => {
    const handler = (event) => setState(event.val);
    window.addEventListener(useHookEvent, handler);
    return () => window.removeEventListener(useHookEvent, handler);
  }, []);
  return [
    state,
    useCallback((val) => {
      const event = new Event(useHookEvent);
      event.val = val;
      dispatchEvent(event);
    }, [])
  ];
};
```

**Comment by amorawski** [comment]
Great, thank you. I made invalid assumptions thus the confusion. We can close this issue now.
