### ISSUE TITLE
[feature] memory router?

### ISSUE THREAD

**Issue by KutnerUri** [molefrog/wouter#246]
MemoryRouter is a great way to work with routes in Tests, and in sub-apps (like iframes).
I could only find static routing, so I wrote this one down. What do you think?

```tsx
import {
    ReactNode,
    useState,
    useCallback,
    createContext,
    useContext,
} from "react";
import  { Router, RouterProps, Path } from "wouter";

type NavFunc = (to: Path, options?: { replace?: boolean }) => void;
const MemoryLocationCtx = createContext<Path>("/");

export function useMemoryHook(path: Path[] = ["/"], { maxHistory = 100 } = {}) {
    const [history, setHistory] = useState<Path[]>(path);

    let useLocationHook: { (): [Path, NavFunc]; history?: any };
    const navigate: NavFunc = useCallback(
        (to: Path, { replace }: { replace?: boolean } = {}) => {
            setHistory(history => {
                const nextHistory = history.slice(0, maxHistory);

                if (replace) nextHistory.pop();
                nextHistory.push(to);

                return nextHistory;
            });
        },
        [maxHistory]
    );

    useLocationHook = () => {
        const location = useContext(MemoryLocationCtx);
        return [location, navigate];
    };
    useLocationHook.history = history;

    return useLocationHook;
}
interface InMemoryRouterProps extends Partial<Omit<RouterProps, "hook">> {
    children: ReactNode;
    initialPath?: Path | Path[];
}

export function MemoryRouter({ initialPath, ...props }: InMemoryRouterProps) {
    const inMemHook = useMemoryHook(
        typeof initialPath === "string" ? [initialPath] : initialPath
    );
    const location = inMemHook.history.slice(-1).pop();

    return (
        <MemoryLocationCtx.Provider value={location}>
            <Router hook={inMemHook} {...props} />
        </MemoryLocationCtx.Provider>
    );
}
```

**Comment by KutnerUri** [comment]
also - it seems the use location hook is parsing window.location into a local state in every usage?
why not do it once in a centralized place and get it from context?

**Comment by molefrog** [comment]
> MemoryRouter is a great way to work with routes in Tests, and in sub-apps (like iframes). I could only find static routing, so I wrote this one down. What do you think?
> 
> ```tsx
> import {
>     ReactNode,
>     useState,
>     useCallback,
>     createContext,
>     useContext,
> } from "react";
> import  { Router, RouterProps, Path } from "wouter";
> 
> type NavFunc = (to: Path, options?: { replace?: boolean }) => void;
> const MemoryLocationCtx = createContext<Path>("/");
> 
> export function useMemoryHook(path: Path[] = ["/"], { maxHistory = 100 } = {}) {
>     const [history, setHistory] = useState<Path[]>(path);
> 
>     let useLocationHook: { (): [Path, NavFunc]; history?: any };
>     const navigate: NavFunc = useCallback(
>         (to: Path, { replace }: { replace?: boolean } = {}) => {
>             setHistory(history => {
>                 const nextHistory = history.slice(0, maxHistory);
> 
>                 if (replace) nextHistory.pop();
>                 nextHistory.push(to);
> 
>                 return nextHistory;
>             });
>         },
>         [maxHistory]
>     );
> 
>     useLocationHook = () => {
>         const location = useContext(MemoryLocationCtx);
>         return [location, navigate];
>     };
>     useLocationHook.history = history;
> 
>     return useLocationHook;
> }
> interface InMemoryRouterProps extends Partial<Omit<RouterProps, "hook">> {
>     children: ReactNode;
>     initialPath?: Path | Path[];
> }
> 
> export function MemoryRouter({ initialPath, ...props }: InMemoryRouterProps) {
>     const inMemHook = useMemoryHook(
>         typeof initialPath === "string" ? [initialPath] : initialPath
>     );
>     const location = inMemHook.history.slice(-1).pop();
> 
>     return (
>         <MemoryLocationCtx.Provider value={location}>
>             <Router hook={inMemHook} {...props} />
>         </MemoryLocationCtx.Provider>
>     );
> }
> ```

I like the idea! We don't have plans on making memory router part of the package tbh... but if you ever publish this as a separate package please let me know, I'll be happy to promote it.

Closing this for now.
