### ISSUE TITLE
[Request] Add a hook that returns the current route with all params

### ISSUE THREAD

**Issue by Industrial** [molefrog/wouter#248]
Hi!

I am creating a Breadcrumb component. This component needs to know about the whole route tree.

These are my routes (for now):

```
/list
/list/:listId
/list/:listId/:todoId
/project
/project/:projectId
/tag
/tag/:tagId
```

Using `useRoute` I need to make a match for every route:

```ts
  const [listListMatch, listListParams] = useRoute('/list');
  const [listShowMatch, listShowParams] = useRoute('/list/:listId');
  const [todoShowMatch, todoShowParams] = useRoute('/list/:listId/:todoId');
  const [projectListMatch, projectListParams] = useRoute('/project');
  const [projectShowMatch, projectShowParams] = useRoute('/project/:projectId');
  const [tagListMatch, tagListParams] = useRoute('/tag');
  const [tagShowMatch, tagShowParams] = useRoute('/tag/:tagId');
```

I want a hook that returns the current route with all params so I can dynamically build my components. Is that possible?

**Comment by cbbfcd** [comment]
if i understand correctly, it's possible. you can make your custom [`matcher`](https://github.com/molefrog/wouter/blob/master/index.js#L37) to support more complex `regexp` match. like this

```js
useRoute('/(tag | list | project)/:id/:subId')
```

given the flexibility of wouter, there should be other workrounds here

**Comment by Industrial** [comment]
Thanks, that worked.

**Comment by rvision** [comment]
Does anyone have an example of matcher that extracts all patterns from given routes? Without code duplication, just from <Route /> definitions? And based on that, breadcrumbs list of objects and parameters?

Thanks
