### ISSUE TITLE
[Enhancement] - Possible Code Reduction

### ISSUE THREAD

**Issue by abjfdi** [molefrog/wouter#254]
## Background
The flattenChildren method uses the reduce - map pattern on MDN [Array.prototype.flat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat) docs. MDN [Array.prototype.flatMap](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap) is the same pattern but claims to be slightly faster and is less code.

https://github.com/molefrog/wouter/blob/467d8b2fb4bea48d5f6686743a785f7c87a2e5ad/index.js#L134

I took the time to change the function if your interested in this code change. Also flattenChildren was written twice, below solution writes it once.

```javascript
const flattenChildren = children => {
    return Array.isArray(children)
        ? children.flatMap(c => flattenChildren(c && c.type === Fragment ? c.props.children : c))
        : [children];
};
```

**Comment by cbbfcd** [comment]
compatibility issues worth considering, [can i use `flatMap`](https://caniuse.com/?search=flatMap)

**Comment by abjfdi** [comment]
Yes that is an issue worth considering. I don't know what browsers wouter is trying to support. You can close this issue if you want.

**Comment by abjfdi** [comment]
Another issue worth considering is that the flattenChildren function is a core piece of wouter and any changes to it should come with serious considerations and regression testing.
