### ISSUE TITLE
[feature] Wrap Link with forwardRef

### ISSUE THREAD

**Issue by avionbg** [molefrog/wouter#256]
There are cases where we need a working ref to rendered link dom node, it would really be helpful if this gets into the code.

**Comment by cbbfcd** [comment]
can you tell me what the scene is?

**Comment by avionbg** [comment]
Most typical example would be MUI <Button component={Link} /> - which fails due to the missing ref.

**Comment by trymoto** [comment]
Same here, would be useful with MUI

**Comment by trymoto** [comment]
@cbbfcd I can go ahead and create a pr if it's ok, should be pretty straightforward.

**Comment by molefrog** [comment]
This has been implemented and released in https://github.com/molefrog/wouter/releases/tag/v2.8.0

Thanks @trymoto for your help!
