### ISSUE TITLE
Docs: Missing useLocation options

### ISSUE THREAD

**Issue by neutraali** [molefrog/wouter#258]
When looking at the [docs for useLocation](https://github.com/molefrog/wouter#uselocation-hook-working-with-the-history), one would think that you can't pass any options for the `setLocation` -hook regarding navigation.

However, when looking at the [actual source code](https://github.com/molefrog/wouter/blob/master/use-location.js#L50), you actually can pass the crucial `{ replace: true }` -option, which is sometimes needed when dealing with the browser's "back" -button for example.

I think it would be worth mentioning in the docs.

**Comment by cbbfcd** [comment]
nice catch
