### ISSUE TITLE
Missing type declaration for the new Router prop `parent`

### ISSUE THREAD

**Issue by waful** [molefrog/wouter#270]
https://github.com/molefrog/wouter/blob/main/types/ts4.1/index.d.ts#L125

I'm getting a ts error saying that `parent` doesn't exist on the Router type, which makes sense because it isn't declared in RouterProps. Unfortunately I am too new to typescript to be confident in contributing a fix.

**Comment by HansBrende** [comment]
Ah yes, looks like updating types was missed in https://github.com/molefrog/wouter/pull/265. 

@molefrog FYI ^^^

**Comment by molefrog** [comment]
Ah, that's right. On it.

**Comment by molefrog** [comment]
Please see #274
