### ISSUE TITLE
Proposal, Enhancement: Loaders

### ISSUE THREAD

**Issue by PodaruDragos** [molefrog/wouter#271]
Hello,
I would be really nice if `wouter` will also support async loaders like `react-router` and now `@tanstack/react-router` 

Proposal, close to `react-router`

```

const loaderDataFunction = async (params): Promise<void> => {
  return await Promise.resolve(params.id);
}

<Route
  loader={loaderDataFunction}
>

const data = useLoaderData();
```

Data prefetching is a good addition to any router and I think it will benefit all of the community.
Let me know what you think.

**Comment by HansBrende** [comment]
@PodaruDragos out of curiosity, why not simply do something like this:

```typescript
<Route path="/posts/:id">{({id}) => <PostForId id={id}/>}</Route>

function PostForId({id}) {
    const {data, loading, error} = usePostForId(id); // <-- React Query hook
    return loading ? "Loading..." : error ? "Error!" : <PostForData data={data}/>
}
```

Is there an advantage of the loader function pattern that you couldn't achieve just as easily following the above approach?

**Comment by anri-asaturov** [comment]
I found wouter because react-router has become bloated with things like loaders and now looks more like frontend framework. And first issue I see here is proposal to add loaders :-D

**Comment by molefrog** [comment]
> Hello, I would be really nice if `wouter` will also support async loaders like `react-router` and now `@tanstack/react-router`
> 
> Proposal, close to `react-router`
> 
> ```
> 
> const loaderDataFunction = async (params): Promise<void> => {
>   return await Promise.resolve(params.id);
> }
> 
> <Route
>   loader={loaderDataFunction}
> >
> 
> const data = useLoaderData();
> ```
> 
> Data prefetching is a good addition to any router and I think it will benefit all of the community. Let me know what you think.

Hi @PodaruDragos, thanks for raising this up. We don't have plans currently for adding a support for this, but that doesn't mean you can't use async routes. Wouter should play well with things like suspense. 

I played around with async routes in this sandbox, you might find it helpful:
https://codesandbox.io/s/wouter-suspense-nyp5t?file=/index.js

**Comment by pastelmind** [comment]
@molefrog Hi, unfortunately your example does not work with Wouter v3--switching between tabs shows the "global app loading..." suspense fallback message.

I tested with previous versions of wouter, and it seems that wrapping `setLocation()` with `startTransition()` stopped working with wouter [2.10.0](https://github.com/molefrog/wouter/releases/tag/v2.10.0). This was when wouter switched to `useSyncExternalStore()`, so I assume it may have something to do with it?

Edit: I found a solution using [`useDeferredValue()`](https://react.dev/reference/react/useDeferredValue):

```tsx
const useDeferredBrowserLocation: typeof useBrowserLocation = (...args) => {
  const [location, setLocation] = useBrowserLocation(...args);
  const deferredLocation = useDeferredValue(location);

  return [deferredLocation, setLocation];
}

const App = () => (
  <Suspense fallback={"global app loading..."}>
    <Router hook={useDeferredBrowserLocation}>
      <div className="App">
        {/* ... */}
      </div>
    </Router>
  </Suspense>
);
```

(See full example: https://codesandbox.io/p/sandbox/wouter-use-deferred-value-lwssn9)

This works with Wouter 3.2.0 and React 18.2. You don't need to wrap `setLocation()` with `startTransition()` for this to work.

In fact, you don't need `<Suspense>` either! I tested it without `<Suspense>` and it works fine, though there is an empty screen during the initial load.

**Comment by molefrog** [comment]
@pastelmind Perfect, I think your solution is legit! If you'd like, you can fire a PR to document this approach in the README.

**Comment by azuline** [comment]
useSyncExternalStore de-opts a state update from time slicing, so it is useless to wrap the state update in startTransition, because startTransition configures the priority of time slices. this caused the v2.9.1 suspense implementation to break in v2.10.

the reason to de-opt from time slicing is to solve tearing, which mutable state and time slicing together cause. however, I'm unworried about tearing as a result of a location state update, since location updates usually cause a full page transition. i would rather have time slicing and suspense than solve for the rare occasional tear. i have remained on wouter v2.9.1 for this reason.

but now i can upgrade! thanks for the useDeferredValue solution!
