### ISSUE TITLE
Question: HOC with Typescript

### ISSUE THREAD

**Issue by ev3nst** [molefrog/wouter#273]
I want to use "useLocation" in my class component with typescript. So far i have gotten to this point with looking at the example at #135

````typescript
export type UseLoc = {
  useLoc: [
    string,
    (
      to: string,
      options?:
        | {
          replace?: boolean | undefined;
        }
        | undefined
    ) => void
  ];
};

export function withUseLocation<T>(Component: ComponentType<T>) {
  return (hocProps: T) => {
    const useLoc = useLocation();

    // eslint-disable-next-line react/jsx-props-no-spreading
    return <Component {...(hocProps as T)} useLoc={useLoc} />;
  };
}



// in class component
const { useLoc } = this.props as IProps & UseLoc;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const [location, setLocation] = useLoc;
setLocation(`/test`);
````

This is the workaround im using right now im just wondering if there is any better way to do it without so much ugly syntax.

**Comment by cbbfcd** [comment]
What about trying to use Provider? distribute the exposed capabilities of the `wouter` uniformly at the top level to avoid using `HOC`

**Comment by molefrog** [comment]
I can't think of a better way to achieve this than what @cbbfcd has proposed. I'm closing this issue for now, feel free to reopen if you have more questions!
