### ISSUE TITLE
Please don't tag alphas as 'latest' on npm

### ISSUE THREAD

**Issue by silverwind** [molefrog/wouter#278]
A `npm install wouter` will by default install the `latest` tag, but this [currently points to the latest alpha](https://www.npmjs.com/package/wouter?activeTab=versions) which I think is not something most people would want to install by default.

Suggesting to create a separate npm tag for unstable versions, e.g. `next` is pretty common for this. See for example the [react package](https://www.npmjs.com/package/react?activeTab=versions) which also does not promote unstable versions to `latest`.

**Comment by molefrog** [comment]
Hi! Sorry, that was my fault 😞 I had little experience with dist-tags, wasn't aware that npm automatically applies `latest` when new version gets published.

Fixed:
<img width="793" alt="image" src="https://user-images.githubusercontent.com/671276/213666239-4fb690f8-2c15-4246-9c50-cb6036e85ab1.png">
