### ISSUE TITLE
Hash router with React 16

### ISSUE THREAD

**Issue by pekanboy** [molefrog/wouter#281]
Hello! In my project using react 16. It don`t support the useSyncExternalStore.
How can i use hash router without use useSyncExternalStore,  thanks for answer

**Comment by HansBrende** [comment]
@pekanboy you don't need it at all. Looks like the example in the README was not fully cleaned up to remove the `useSyncExternalStore` import. But if you look closely, that import is not used anywhere in the example.

**Comment by molefrog** [comment]
@pekanboy There was an unused import in the README indeed. Thank you for pointing out, I fixed that. 
Also, the example in the README refers to the alpha version of wouter `2.10.0` which is yet to be released, for the older versions, refer to the CodeSandbox demo.
