### ISSUE TITLE
Support for TypeScript moduleResolution: "node16"

### ISSUE THREAD

**Issue by toerndev** [molefrog/wouter#283]
TypeScript currently cannot detect wouter's types if `moduleResolution` is set to `"node16"` or `"nodenext"`.

This seems to be fixed by referencing the type files for each element under `exports`:
```json
".": {
  "types": "./types/ts4.1/index.d.ts",
  "require": "some path",
  "default": "some path"
},
"/use-location": "same idea as above"
```
and so on. **types** has been added. Is this something that could be added safely?
If not, I think the same result is achieved by ensuring that the `.d.ts` files are located next to their JS counterparts (but they aren't in wouter).

Here's a [long discussion](https://github.com/microsoft/TypeScript/issues/50794) about this issue from TypeScript's perspective.
Here's [an example](https://github.com/andrewbranch/example-subpath-exports-ts-compat) of how you're supposed to export subpath types according to Microsoft's module resolution guy.

It's a bit over my head right now, I wish I could explain exactly how it works. :slightly_smiling_face: 
Also the current package.json seems pretty deliberate so I could be totally wrong.

FWIW it _seems_ like when the modern & upcoming module resolution is enabled, `exports` takes precedence and it becomes necessary to define the types there too. And it sounds like the new way will be the default eventually.

**Comment by toerndev** [comment]
> pr welcome

Sure, done!
Wasn't sure whether it's the best solution or if you'd want it, but after thinking a bit I don't see what problems it could cause.
Feel free to close this. :-)

**Comment by molefrog** [comment]
Released in https://github.com/molefrog/wouter/releases/tag/v2.10.0
