### ISSUE TITLE
[Question] Specific layout only in routes other than the default route

### ISSUE THREAD

**Issue by jinmayamashita** [molefrog/wouter#284]
Is there a recommended implementation in wouter for including a specific layout only in routes other than the default route (Not found page) and not in the default route?

I couldn't find it in the documentation.

I was able to get the intended implementation with the following sample
but if there is an easier way, I would appreciate it if you could let me know.

code: https://codesandbox.io/s/admiring-fermi-vi8uf1?file=/src/App.tsx

**Comment by molefrog** [comment]
@jinmayamashita I would suggest moving `Layout` component inside of the switch by creating a custom route component, e.g. `RouteWithLayout`. Switch in wouter doesn't really check the type of the children element, it only tries to locate a `path` prop on it. But this of course has some implications, such as there might be some extra rendering of `Layout`.

https://codesandbox.io/s/wouter-layout-in-switch-5vy0nw
