### ISSUE TITLE
Support ref forwarding with Link (update props types)

### ISSUE THREAD

**Issue by HugoGresse** [molefrog/wouter#287]
To use the Link component with MaterialUI, we need ref forwarding, but Link does not have a ref prop am I right? 

```
import {Link as RouterLink, LinkProps} from "wouter"
const LinkBehavior = React.forwardRef<any, Omit<RouterLinkProps, 'to'>>(
  (props, ref) => (
    <RouterLink
      ref={ref}
      to="/material-ui/getting-started/installation/"
      {...props}
    />
  ),
);
```

**Comment by molefrog** [comment]
> To use the Link component with MaterialUI, we need ref forwarding, but Link does not have a ref prop am I right?
> 
> ```
> import {Link as RouterLink, LinkProps} from "wouter"
> const LinkBehavior = React.forwardRef<any, Omit<RouterLinkProps, 'to'>>(
>   (props, ref) => (
>     <RouterLink
>       ref={ref}
>       to="/material-ui/getting-started/installation/"
>       {...props}
>     />
>   ),
> );
> ```

As far as I remember, you can! Take a look at this PR https://github.com/molefrog/wouter/pull/259

**Comment by HugoGresse** [comment]
I think the props-types may be wrong (in TS), I'm unsure about what is the exact issue though. I wanted to follow MUI Link integration: https://mui.com/material-ui/react-link/#third-party-routing-library

**Comment by molefrog** [comment]
> I think the props-types may be wrong (in TS), I'm unsure about what is the exact issue though. I wanted to follow MUI Link integration: https://mui.com/material-ui/react-link/#third-party-routing-library

You were absolutely right, the exported type for `Link` was missing the ref type. I'll make sure to fix it, in the meantime here is a workaround:

https://codesandbox.io/s/broken-firefly-yo6f7e?file=/demo.tsx

**Comment by HugoGresse** [comment]
Thanks @molefrog 
I think there is still an issue with this sample: 
![image](https://user-images.githubusercontent.com/662377/221870547-1866acb4-cd31-4bc4-aacd-036bab974373.png)

**Comment by molefrog** [comment]
> Thanks @molefrog I think there is still an issue with this sample: ![image](https://user-images.githubusercontent.com/662377/221870547-1866acb4-cd31-4bc4-aacd-036bab974373.png)

Can you reproduce it in the sandbox I shared earlier? It doesn't give me an error...

**Comment by molefrog** [comment]
I would take a guess this is the reason:

```diff
- <RouterLink ref={ref} to={href} {...other} />
+ <RouterLink ref={ref} href={href} {...other} />
```

**Comment by HugoGresse** [comment]
I found the issue, the type was missing an omit 

Before:  `  Omit<WouterLinkProps, 'to'> & { href: WouterLinkProps['to'] }` 
After: `Omit<Omit<WouterLinkProps, "to">, "href"> & { href: string }`
