### ISSUE TITLE
`undefined` location exception in SSR mode useLocation hook call

### ISSUE THREAD

**Issue by Mati365** [molefrog/wouter#288]
In ssr mode this default location argument assign raises `undefined` exception:
https://github.com/molefrog/wouter/blob/main/use-location.js#L7

`location` object is not defined in `ssr` env. It used to fail in strict mode TS compile mode.

**Comment by molefrog** [comment]
Hi @Mati365, could you please check if it's related to this #286

**Comment by Mati365** [comment]
Probably it's related.
