### ISSUE TITLE
Redirect not work in SSR mode in 2.9 version using React 18

### ISSUE THREAD

**Issue by Mati365** [molefrog/wouter#293]
This code:

```tsx
<Redirect to='/login' />
```

is not triggering redirect in SSR (on client side it is working correctly). Probably because used for example here:

https://github.com/molefrog/wouter/blob/efda2abc95bdb8b01d9d55b865078fbae63c4a2b/index.js#L188

`useIsomorphicLayoutEffect` hook is not being called in SSR mode (using React 18.x). `navigation` seems not to be working too.

Workaround:

```tsx
export const Redirect = ({ to }: RedirectProps) => {
  const [, navigate] = useLocation();
  const router = useRouter();

  if (isSSR()) {
    (router.hook as any).history.push(concatUrls(router.base, to));
  }

  useAfterMount(() => {
    navigate(to);
  });

  return null;
};
```

**Comment by cbbfcd** [comment]
the problem may be here: https://github.com/molefrog/wouter/blob/efda2abc95bdb8b01d9d55b865078fbae63c4a2b/use-location.js#L41

**Comment by Mati365** [comment]
it is still broken in 2.11

**Comment by molefrog** [comment]
Closing this in favour of https://github.com/molefrog/wouter/issues/468 (which is for v3)
