### ISSUE TITLE
wouter-preact package version (v2.10.0-alpha.1) is slightly out of sync with wouter (v2.10.0)

### ISSUE THREAD

**Issue by robertknight** [molefrog/wouter#294]
Thank-you for this package. The Preact version (`wouter-preact`) is slightly out of sync (v2.10.0-alpha.1) with the React version (v2.10.0). I'm not certain from looking at [the diff](https://github.com/molefrog/wouter/compare/v2.10.0-alpha.1...v2.10.0) whether there are any relevant changes for Preact users, but it would be great if the Preact version could be updated to the latest.

**Comment by molefrog** [comment]
Thank you, I intentionally didn't publish the latest version bc there are still some unfinished typings that we haven't migrated to Preact. It's become a bit cumbersome to support both Preact / React / TS3.9 / TS4.1 so some features end up being out of sync 😞

**Comment by molefrog** [comment]
The new version is almost ready, could you please verify that `2.11.0-dev.2` works?

**Comment by molefrog** [comment]
Published `wouter-preact@2.11.0` which should be up-to-date!
