### ISSUE TITLE
The Redirect in pair with switch is broken

### ISSUE THREAD

**Issue by nikita-starostin** [molefrog/wouter#295]
Hi, I have created new react app with `create-react-app`, installed the latest wouter and create the skeleton of the project, that is App.tsx
```
import React from 'react';
import { Redirect, Route, Switch } from 'wouter';
import './App.css';
import Ipr1 from './ipr1/ipr1';
import Ipr2 from './ipr2/ipr2';


export default function App() {
  return (
    <>
      <Switch>
        <Route path="">
          <Redirect to="/ipr1"/>
        </Route>
        <Route path="/ipr1">
          <Ipr1/>
        </Route>
        <Route path="/ipr2">
          <Ipr2/>
        </Route>
      </Switch>
    </>
  );
}

```

I was struggling for 15 minutes trying to understand, why `Ipr1` component is not shown, the fixes I have found are:
1. remove Switch
2. remove Redirect
3. move "" route to the bottom

I have found it is a little bit confusing, when I see in the browser /ipr1, but don't see rendered Ipr1 component, maybe it works as designed.

Maybe would be nice to add a note about such behaviour in that section of readme
![image](https://user-images.githubusercontent.com/57386894/223511426-68272f10-247c-40d0-a71d-069571dba53c.png)

to reproduce you can check that branch: https://github.com/nikita-starostin/bsuir-cos/tree/wouter_issue 
(it is small and could be opened and run with codespace)

**Comment by molefrog** [comment]
Yep, that's an intended behaviour. Any route with empty `path` prop is considered active, so when it goes as a first child in Switch, it will be rendered no matter what. And then Switch stops looking for other matches so the further routes aren't checked even though they match the current location.

I've added some clarification in the README https://github.com/molefrog/wouter/commit/79bf0f22c24143e9ee89ea3adec42f7d294b3bd8

Thanks!
