### ISSUE TITLE
Take the Router Challenge

### ISSUE THREAD

**Issue by grahammendick** [molefrog/wouter#296]
[The Router Challenge](https://github.com/grahammendick/router-challenge) aims to be to Routers what TodoMVC was to MV* frameworks. It offers the same Music Catalog application built in React using different Routers. For it to be successful I need the help of Router writers like you. Will you [take the Router Challenge](https://github.com/grahammendick/router-challenge/blob/master/CONTRIBUTING.md) and implement the Music Catalog application using wouter, please?

**Comment by molefrog** [comment]
Hi! Thank you for your invitation. I'm a bit limited with my free time to work on the project at the time, so I would pass on that at least for how. 

But it would be nice if someone could make that demo, I would be happy to promote it in the README when they do.
