### ISSUE TITLE
@rollup/plugin-replace incorrectly listed as a dependency

### ISSUE THREAD

**Issue by davidje13** [molefrog/wouter#299]
The `@rollup/plugin-replace` dependency should be a `devDependency` - it is not needed at runtime. ([added here](https://github.com/molefrog/wouter/commit/f9f7ea7b555d0017c6143aab04115549c915637e)).

(see https://www.npmjs.com/package/wouter?activeTab=dependencies)

**Comment by molefrog** [comment]
> The `@rollup/plugin-replace` dependency should be a `devDependency` - it is not needed at runtime. ([added here](https://github.com/molefrog/wouter/commit/f9f7ea7b555d0017c6143aab04115549c915637e)).
> 
> (see https://www.npmjs.com/package/wouter?activeTab=dependencies)

You're right! Mind raising a PR to fix that?

**Comment by davidje13** [comment]
Created #301
