### ISSUE TITLE
Add new examples to the README

### ISSUE THREAD

**Issue by molefrog** [molefrog/wouter#3]
- How to use `useRouter` and do redirects
 - Different ways to create a link

**Comment by helderburato** [comment]
I can help with that. :D

**Comment by molefrog** [comment]
Hi @helderburato! Do you still want to help with the README?

I have some ideas in mind and was planning to add a whole new section to it called **FAQ & Recipes**, that will cover additional topics like SSR, Redirects and basically contain some code recipes. I intentionally plan not to add these things to the source code of the library, since I want this to be as small as possible. However, would be nice to provide people with short code samples that will allow them to implement these features themselves. 

I can draft out a structure of the updated README doc, but I'll need some help reviewing it.

**Comment by helderburato** [comment]
Nice to know that! @molefrog 
I still can help with the revision 💯

**Comment by molefrog** [comment]
Hey @helderburato, thanks for offering the help, but the README has already been proofread. I'm releasing a new version soon, so I had to rewrite some part of it.

But please don't hesitate to open an issue or PR if you see that it can be improved!
