### ISSUE TITLE
`index.d.ts` contains unnecessary types re-exports

### ISSUE THREAD

**Issue by Mati365** [molefrog/wouter#304]
VScode (and eslint) allows me to import `import { useSearch } from 'wouter';` but it raises `(0 , wouter_1.useSearch) is not a function` in runtime. 

Workaround:
```tsx
import { useSearch } from 'wouter/use-location';
```

Affected version: 2.10.1.

**Comment by molefrog** [comment]
Hi! `useSearch` is exported from `wouter/use-location` which is a separate module that implements browser location hook. Search params are not first-class citizens (yet!), so we decided to separate the main module that can work with any location-like hooks (hash-routing, localstorage, local state for example) and the module that handles specifically location in the browser URL bar. 

I've got some plans to abstract search parameters that can be implemented by specific hooks passed to a Router, but that will involve some breaking changes.

**Comment by molefrog** [comment]
> It should not be closed. Typings that are exported from the package should never ever allow us to import that one method. Something is messed up.

Ok, sorry I overlooked that. Let me dig into it.

**Comment by molefrog** [comment]
You are right, for some reason there is a re-export of types in the main `d.ts` file, which can be dropped I assume.

**Comment by molefrog** [comment]
The fix has been published in `2.11.0-alpha.1`, please give it a try.
