### ISSUE TITLE
preact types declarations

### ISSUE THREAD

**Issue by jerssonM** [molefrog/wouter#309]
wouter in preact have problems with the typings, I receive this error using typescript 5 and  wouter-preact: 2.10.0-alpha.1

`
Could not find a declaration file for module 'wouter-preact'. 'node_modules/.pnpm/wouter-preact@2.10.0-alpha.1_preact@10.13.1/node_modules/wouter-preact/index.js' implicitly has an 'any' type.
`

**Comment by molefrog** [comment]
Hi @jerssonM, the preact version is slightly out of date. I'm working on a fix, in the meantime could you please check if installing `2.11.0-dev.2` solves the issue?

**Comment by jerssonM** [comment]
> Hi @jerssonM, the preact version is slightly out of date. I'm working on a fix, in the meantime could you please check if installing `2.11.0-dev.2` solves the issue?

Yes!! the new version resolve my problem.
Do you recommend me to use that version or maybe another stable version like `2.9.0`?
