### ISSUE TITLE
Can't lazy load and have a 404 page at the same time

### ISSUE THREAD

**Issue by s1nistr4** [molefrog/wouter#313]
When trying to use the <Switch> tag with the <Suspense> tag, the routes tags aren't detected and making a fallback page isn't possible to do.

**Comment by molefrog** [comment]
hi! Could you provide an example of your code?

**Comment by s1nistr4** [comment]
Sorry, completely forgot

In App.tsx
 `
import { Suspense } from "react"
import { Switch, Route } from "wouter"

// Load components in 
const Home:LazyExoticComponent<any> = lazy(() => import("./pages/Home").then((module) => ({ default: module.Home })))
const About:LazyExoticComponent<any> = lazy(() => import("./pages/About").then((module) => ({ default: module.About })))
const NotFound:LazyExoticComponent<any> = lazy(() => import("./pages/NotFound").then((module) => ({ default: module.NotFound })))

function App():ReactElement {
     return (
      <>
        <Switch>
            <Suspense fallback={fallback}>  <Route path="/" component={Home} /> </Suspense>
            <Suspense fallback={fallback}>  <Route path="/about" component={About} /> </Suspense>
            <Suspense fallback={fallback}>  <Route path="/:rest*" component={NotFound} /> </Suspense>
        </Switch>
     </>
    )
}

export default App
`

I think what's going on is that the switch statement is not recognizing the React suspense tag, causing it to not recognizethe routes. If you remove the suspense tags, it works, but then you also don't get lazy loading.

**Comment by molefrog** [comment]
Would it work if you wrap the switch with suspense and not the individual routes? You are right about Switch not recognizing Suspense as its child routes, because switch basically looks for any child with `path` prop and renders the first one that matches the pattern.
