### ISSUE TITLE
Combine location based routing with hash based routing

### ISSUE THREAD

**Issue by mvdenk** [molefrog/wouter#317]
Hi, 

I was wondering if there are any examples or plans to support location - and hash based routing side by side. 

My use case is as follows:

I use normal routing for most of the app: 
e.g.: `/orders`

On some pages I use tabs, and I'm using hashes to support deep linking, which is actually working quite nice.
e.g.: `/orders#completed`

For the back button to work, Wouter should **also** listen to changes in hash. Would be nice if someone can point me in the right direction.

Thanks in advance.

**Comment by molefrog** [comment]
You can use wouter as is for most of your app's routes, and then for the part where you need to control hash location use a standalone `useHashLocation` hook which you can implement as:

```js
// returns the current hash location in a normalized form
// (excluding the leading '#' symbol)
const hashLocation = () => window.location.hash.replace(/^#/, "") || "/";

// this is from the example in the README, however it won't create a new history entry, so you need pushState
// const hashNavigate = (to) => navigate("#" + to);

const hashNavigate = (to) => history.pushState({}, "", location.pathname + "#" + to)

const useHashLocation = () => {
  const location = useLocationProperty(hashLocation);
  return [location, hashNavigate];
};

```

**Comment by molefrog** [comment]
Hi @mvdenk! Did it solve your issue?
