### ISSUE TITLE
NestedRouter docs are misleading

### ISSUE THREAD

**Issue by justin-hackin** [molefrog/wouter#321]
You can't use a `NestedRouter` inside a `Router` because, as in the readme example, at route `/app/dashboard` the `parentLocation` will be `/dashboard` but the `nestedBase` will be `/app/dashboard` leading to the component always returning null. The readme is out of sync with the linked codesandbox which seems to indicate this. Is there a way to achieve multiple levels of nested routes? I can't seem to achieve this with the demo.

**Comment by antgonzales** [comment]
@justin-hackin Can you provide a code example/sandbox link? I think you have the `parentLocation` and `nestedBased` swapped. Here's what I see when I log those values in the example:

<img width="1764" alt="Screenshot 2023-06-21 at 3 22 31 PM" src="https://github.com/molefrog/wouter/assets/3740655/a5040831-4ee5-4939-a8e8-6ad99ce3777c">

**Comment by molefrog** [comment]
Thank you for reporting this. The docs have been updated: https://github.com/molefrog/wouter/tree/main#are-relative-routes-and-links-supported

The current recipe for route nesting isn't ideal, but I'm working on a newer nesting spec for `v3` that will not require `parent` prop and will support dynamic nesting, e.g. nesting "/users/:id"
