### ISSUE TITLE
(Question) How to set 404 when use nested routes ? 

### ISSUE THREAD

**Issue by gusma296** [molefrog/wouter#327]
i didn't find it in the documentation.
i found an example https://codesandbox.io/s/wouter-demo-nested-routes-ffd5h but this doesn't solve my problem, because in this example the 404 page is inside nested routes.
I'm expecting that 404 page to handle all routes

**Comment by molefrog** [comment]
Hi @gusma296, you can't use 404 inside nested routes in this example because the `Scope` component won't render if the page is out of scope. You have to introduce a top-level switch with default route if you want to have a global 404 page.

**Comment by molefrog** [comment]
I have updated [the sandbox](https://codesandbox.io/s/wouter-demo-nested-routes-ffd5h) to illustrate how you can use the top-level 404 along with the scoped 404 page.
