### ISSUE TITLE
/main not matching /main/xxx/xxx nested route

### ISSUE THREAD

**Issue by linonetwo** [molefrog/wouter#328]
```tsx
<Route path={`/${WindowNames.main}`} component={Main} />
```

And in Main

```tsx
          <Switch>
            <Route path={`/${WindowNames.main}/${PageType.wiki}/:id/`} component={WikiBackground} />
            <Route path={`/${WindowNames.main}/${PageType.workflow}/:id/`} component={Workflow} />
            <Route path={`/${WindowNames.main}`} component={WikiBackground} />
            <Route>
              <div>{t('Loading')}(Main)</div>
            </Route>
          </Switch>
```

When nevigate to /main/wiki/xxx it become 404, so nested routes are never matched.

**Comment by linonetwo** [comment]
This is a workaround

```tsx
<Route path={`/${WindowNames.main}/:any*/:any*`} component={Main} />
```

or even

```tsx
<Route path={`/${WindowNames.main}/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*/:any*`} component={Main} />
```

If you want to get react-router exact={falxe} behavior...

**Comment by Mati365** [comment]
It'll be faster to fork this project or create another one with an identical API... The total amount of bugs is overwhelming in this poor quality lib.

**Comment by Mati365** [comment]
@molefrog It's brutal but it _is_ useful for these developers who haven't used this lib yet. To be honest - you just ignored critical things like incorrect route matching for weeks but responded immediately to someone who told the truth about quality.

**Comment by molefrog** [comment]
Hi @linonetwo, in wouter (unlike react-router) routes are not nested by default. This means that `<Route path="/main" component={Main} />` will only render when there is an exact match. 

Your workaround is correct, I would maybe suggest using `/main/:any*` instead which is less strict and will match anything that starts with "/main".

However, I think you can use nested routes here. Nested routing is achieved by wrapping your code with `Router` component with custom `base` and `parent` props. See https://github.com/molefrog/wouter#are-relative-routes-and-links-supported and https://github.com/molefrog/wultra/blob/main/src/wouter/RouteWithLocale.tsx#L36

So, in your example, it becomes:

```js
import { Router, useRouter, Route, Switch } from "wouter";

<Router base="/main" parent={useRouter()}>
  <Route path={`/${PageType.wiki}/:id/`} component={WikiBackground} />
  <Route path={`/${PageType.workflow}/:id/`} component={Workflow} />
  <Route path={`/`} component={WikiBackground} />
  <Route>
              <div>{t('Loading')}(Main)</div>
  </Route>
</Router>
```

Hope that answers your questions. I am closing this, feel free to reopen.

**Comment by molefrog** [comment]
@Mati365 
I don't have to be ashamed of not responding to this question in time. 
This wasn't a bug and surely it wasn't critical. 
This has been answered at least couple of times before here and the answer was available in the README (if you find the readme confusing, PRs are welcome).
