### ISSUE TITLE
useParams removed?

### ISSUE THREAD

**Issue by carlflor** [molefrog/wouter#335]
Hi, based on your README, useParams is available, but the actual package I installed doesn't. Is that expected?

**Comment by OndrejHj04** [comment]
Yep I am encoutering the same

**Comment by luxl** [comment]
https://github.com/molefrog/wouter/pull/329#issuecomment-1695136909
try this

**Comment by molefrog** [comment]
Hi everyone!
Sorry we haven't published this version yet. Would you mind using the beta version as @luxl pointed out? I need to get the feedback on the feature first, I would appreciate if you could use it in your projects for about a week. If everything works well, I'll make the new release. Thank you!

**Comment by OndrejHj04** [comment]
No problemo amigo. Thank you for your response, I really enjoy working with Wouter !

**Comment by OndrejHj04** [comment]
> Hi everyone!
> Sorry we haven't published this version yet. Would you mind using the beta version as @luxl pointed out? I need to get the feedback on the feature first, I would appreciate if you could use it in your projects for about a week. If everything works well, I'll make the new release. Thank you!

No problemo amigo. Thank you for your response, I really enjoy working with Wouter !

**Comment by carlflor** [comment]
got it. Thanks for your response! :)

**Comment by r3wt** [comment]
@molefrog where can we give feedback for useParams. doesn't seem appropriate for me to res this thread

**Comment by molefrog** [comment]
@mnik01 Thank you for reminding. I was initially planning to have more features in this release, but then we started actively working on v3 (which I hope is coming really soon and will include some nice features). I've published `v2.12.0` feel free to use this one.
