### ISSUE TITLE
Can't resolve './react-deps.js' in v1.3.1 & v1.3.2

### ISSUE THREAD

**Issue by timohofmeijer** [molefrog/wouter#34]
wouter v1.3.1 & v1.3.2 can't resolve the `react-depts` dependency.

`Module not found: Error: Can't resolve './react-deps.js' in '/Users/timo/Code/rg/node_modules/wouter'`

**Comment by molefrog** [comment]
Hey @timohofmeijer thanks for reporting this! We forgot to add the file to the list of thing to publish after merging the Preact support. 
I just merged the fix and going to publish a fix soon!

**Comment by timohofmeijer** [comment]
much appreciated!

**Comment by molefrog** [comment]
Ok, just published a new version `v1.3.2`, please check if it does work. 
Unfortunately, I can't republish the package so the `v1.3.0-v1.3.1` will remain untouched.
