### ISSUE TITLE
React is not re-rendeing page when there is query param change

### ISSUE THREAD

**Issue by mnik01** [molefrog/wouter#354]
I have page with url that can be:
`http://localhost:4174/wotc?step=wou` or
`http://localhost:4174/wotc?step=dashboard`

And when I'm navigating to it via <Link href={`?step=${step.path}`}/> React not reacting to changes of URL.

URL is changing, but not UI. It needs page reload to reflect changes. How to fix it? 

https://github.com/molefrog/wouter/assets/39025497/bf78efc8-e2a6-4cc3-92b1-b9d42aa1c52f

**Comment by molefrog** [comment]
The `Link` component you use here, is that the one provided by wouter?
Also, is `getCurrentQueryParam` your own hook or the one you import from `"wouter/use-location"`?

**Comment by mnik01** [comment]
Link from wouter:
`import { Link } from 'wouter';`
function custom:

```tsx
export const getCurrentQueryParams = <T extends Record<string, string>>(url = '') => {
  const queryString = (url || window.location.search).split('?')[1];
  const urlParams = new URLSearchParams(queryString);

  const entries = urlParams.entries();
  const params = {} as T;
  for (const entry of entries) {
    // @ts-expect-error desc
    params[entry[0]] = entry[1];
  }
  return params;
};

```

**Comment by mnik01** [comment]
I can switch to some hook from wouter if it needed for making it work

**Comment by molefrog** [comment]
Right, you should use `useSearch` from "wouter/use-location". If it's not in the README (could you check please?), I will raise an issue.

The reason it didn't work was that your hook doesn't subscribe to location updates, it just reads the value during each render, but won't rerender the component if the location is changed elsewhere.

**Comment by mnik01** [comment]
Thank you! I make it work so:
```ts
const { step = 'dashboard' } = getCurrentQueryParams<{ step: StepType }>(useSearch());
```

> If it's not in the README
I can't find any mention of useSearch in readme :(
