### ISSUE TITLE
Decoding URL params

### ISSUE THREAD

**Issue by jeerbl** [molefrog/wouter#367]
Hi,

I have seen this bug #57, I was wondering if a release that had come out was fixing that?

Jerome

**Comment by molefrog** [comment]
That's actually a really good one, thanks for bringing this up. We will plan this for V3.

**Comment by jeerbl** [comment]
Amazing, thanks @molefrog. Any estimated release date?

**Comment by molefrog** [comment]
There is a published dev release that I am [testing out](https://github.com/molefrog/wultra/commit/0924252aab3245bf4fb3648cb5fd4ac9ccd8579b) in my own projects, however there are things that are blocking us:
- There is going to be a slight breaking change in the `Link` component when we ship `asChild` prop. @jeetiss is currently working on it.
- I am still trying to figure out how to add support for optional wildcards that aren't supported by regexparam yet.

Once things above are resolved, I am going to release the first beta and write a migration guide so you can start using it in your code.

**Comment by jeerbl** [comment]
Beautiful, thanks @molefrog :)
