### ISSUE TITLE
Route not accessible from multiple routers with different base

### ISSUE THREAD

**Issue by waynepurtonsmith** [molefrog/wouter#371]
Take this code an example:

```
const router = useRouter()

<Switch>
  <Route path="/" component={HomePage} />
  <Route path="/some-page" component={ContactPage} />
  <Router base="/a-base-page" parent={router}>
    <Route path="/sub-page-1" component={SubpageOneA} />
    <Route path="/sub-page-2" component={SubpageTwoA} />
    <Route path="/" component={SubpageA} />
  </Router>
  <Router base="/b-base-page" parent={router}>
    <Route path="/sub-page-1" component={SubpageOneB} />
    <Route path="/sub-page-2" component={SubpageTwoB} />
    <Route path="/" component={SubpageB} />
  </Router>
  <Route path="/:rest*">
    {params => <FourOhFour params={params} />}
  </Route>
</Switch>
```

The above code is in `App.tsx` for example, which is wrapped in a router to enable SSR, like so:

```
<Router ssrPath={uri}>
  <App />
</Router>
```

The first route `/a-base-page` and other sub-routes such as `/a-base-page/sub-page-1` is accessible and renders the component, being the first router. However, when accessing `/b-base-page/sub-page-1` on the second router, a blank page is rendered.

Also, if you navigate to `/random-page` the 404 route is rendered, which is correct, but if you go to `/a-base-page/random-page` the 404 page is not rendered, which it should?

Is there something I'm doing wrong that the routes are being configured in the switch?

**Comment by molefrog** [comment]
Hey @waynepurtonsmith, sorry for my late reply. I don't think it is possible mix `Router` with `Switch`. The parent trick is more a workaround to have simple nesting, but it's very limited. 

However! We have just released [v3.0.0-rc.1](https://github.com/molefrog/wouter/releases/tag/v3.0.0-rc.1), where nested routes are natively supported! You can give it a try, there are breaking changes, but they shouldn't take long to resolve. 

I've tried to replicate your [example here](https://codesandbox.io/s/wouter-3-0-0-issue-371-grf3lg?file=/src/index.tsx) and it seems to work.

> but if you go to /a-base-page/random-page the 404 page is not rendered, which it should?

Unfortunately, no, that's not how the Switch works. I can't look deeper that one level, so you will have to introduce a second switch but this time relative to the nested A route.
