### ISSUE TITLE
Wouter 2.0: update types in definitely-typed

### ISSUE THREAD

**Issue by molefrog** [molefrog/wouter#38]
I've just merged the new version 2.0.0 into the master branch and published a `2.0.0-alpha` on npm. Now the types have to be updated. The API is pretty much the same, except that the `history` object is replaced with `useLocation` hook. See README.md for more details.

https://github.com/molefrog/wouter/pull/37/files

**Comment by StrayFromThePath** [comment]
@molefrog Done!
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36330

**Comment by molefrog** [comment]
Thanks @StrayFromThePath! You're the real MVP!
FYI just published a version 2.0.0 of the library.
