### ISSUE TITLE
wouter-preact: Params with typescript?

### ISSUE THREAD

**Issue by Nicolab** [molefrog/wouter#383]
Hello,

There is a typescript error with the url parameters, example:

```tsx
<Route
   path="/confirm/:token"
   component={ConfirmRegister}
 />
```

<img width="708" alt="Capture d’écran 2023-11-11 à 13 00 11" src="https://github.com/molefrog/wouter/assets/1688162/9b4316f7-6b11-4a5b-9219-ebc9cd1a7c83">

--- 

I tried with a function: 

<img width="1006" alt="Capture d’écran 2023-11-11 à 12 58 24" src="https://github.com/molefrog/wouter/assets/1688162/26c90ed7-9cd2-482e-993c-e276a4ce4f86">

--- 
Of course I can use `useParams` but if there is a solution to keep props, I'm interested.
Any idea?

**Comment by molefrog** [comment]
Hi @Nicolab, I can't reproduce this. Could you provide a code sandbox?

**Comment by Nicolab** [comment]
I found my error. 
See my screenshot, with the callback it's the `params` defined `(params)` instead `({params})`.

With the component passed directly, I need to define `token` props as optional. It's not what I want but that works like this, because it's defined like this in Wouter.
