### ISSUE TITLE
How to add params in a nesting route?

### ISSUE THREAD

**Issue by mochetts** [molefrog/wouter#384]
I want to do the following:

```tsx
<Router base="/:slug">
  <Route path="/a" />
  <Route path="/b" />
  <Route path="/c" />
</Router>
```

But this doesn't seem to be working as the base path of the `Router` seems to be taken literally instead of being coherced.

Meaning.. If I go to `localhost:3000/slug-1/a` it doesn't match any route.

**Comment by molefrog** [comment]
Hey! This isn't supported yet, but we're close to releasing the v3 that will have a native support for route nesting with dynamic params:

```js
<Route path="/:slug" nest>
  <Route path="/a" />
  <Route path="/b" />
  <Route path="/c" />
</Route>
```

I expect to publish the first release candidate later this week, so you can start testing it in your project.

**Comment by molefrog** [comment]
See https://github.com/molefrog/wouter/pull/343 and https://github.com/molefrog/wouter/pull/356

**Comment by molefrog** [comment]
The RC is out! See the [announcement](https://github.com/molefrog/wouter/releases/tag/v3.0.0-rc.1).
