### ISSUE TITLE
[Bug] Can't match default <Route>Not found</Route> when Router inside Switch 

### ISSUE THREAD

**Issue by CodingReaction** [molefrog/wouter#394]
Hi, i created an example of the issue. If you try matching "/anything" or "/auth/whatever" it doesn't match with the last one that contains the "Not found" text.

Try commenting the <Router>...</Router> block to see the expected behaviour.
I'm using Google Chrome 120.0.6099.71 on Ubuntu 22 (not sure if is relevant data).

https://replit.com/@CodingReaction/WouterNoMatchError

Did i miss something on the Docs?
Thanks.

**Comment by molefrog** [comment]
Hey, @CodingReaction. I don't think `Router` inside `Switch` is supported. Consider using the [latest version](https://github.com/molefrog/wouter/releases/tag/v3.0.0-rc.2) where nested routing comes out-of-the-box.

**Comment by molefrog** [comment]
Oh, and I'm not completely sure, but this *hack* might help:

```js
<Switch>
    <Route path="/" component={IndexPag} />
    <Router path="/auth/:rest*" base="/auth">
      <Route path="/login" component={LoginPag} />
    </Router>
    <Route>Not found </Route>
  </Switch>
```

Though, I would still prefer the v3.

**Comment by CodingReaction** [comment]
Thanks @molefrog for the clarifications! It's true that Switch doesn't seems to be supported with a Router inside, i think that my previous experience with old versions of react-router-dom contributed to the confusion.

Cheers!
