### ISSUE TITLE
Suggestion: `<Link>` should always render an `<a>` (or at least have the option to do so)

### ISSUE THREAD

**Issue by justingrant** [molefrog/wouter#408]
Currently, `<Link>` not render an `<a>` when its child is a single `ReactElement`, but does render an `<a>` otherwise.

Our team is using `wouter` at scale (overall we love it!) but we've found this behavior to be problematic, for a few reasons:
* Inconsistent presence of `<a>`-specific browser features, like right-clicking to open in a new tab, or copy link address.
* Accessibility is much harder without `<a>`.
* Inconsistent behavior with CSS-in-JS, because styles applied on `<Link>` are applied to the child component's styles applied to the child component. (At least they are with styled-components.) This breaks use cases where two DOM nodes would have different behavior than one DOM node with combined styles, like flex containers, absolute-positioned elements inside relative containers, etc.

The recommended pattern of putting an `<a>` inside a `<Link>` leaves it up to the caller to always remember to do this. In a large team with a large codebase, we've found this to be a common source of errors, especially for new team members who are more familiar with other routing libraries, the vast majority of which always render an `<a>`.

For this reason we stopped using `<Link>` as-is and instead we use a wrapper component that always creates an `<a>`.  I'm not suggesting that the current behavior is always bad, but IMO it's a bad \*default\* behavior because it makes it too easy to create difficult-to-style, inaccessible code.

Would you consider changing the behavior of `<Link>` to always render an `<a>`?  If no, would you consider adding an option to `<Link>` (or a new component) to enable always-render-a-DOM-node behavior?

In case it's helpful to others, below is our current wrapper component. It's missing some features (e.g. `forwardRef`) that we didn't have time to implement yet. 

To make it less likely that users would accidentally import `Link` from wouter (VS Code's auto-import feature makes it trivially easy to make this mistake when other imports from wouter are used), we created a new wrapper package that re-exports all the other wouter exports that we use, and prohibit use of wouter imports elsewhere in our codebase. 

```ts
import React, { isValidElement } from "react";
import { Link as _Link, LinkProps } from "wouter";

export { Router, Route, Params, Switch, Redirect, useLocation, useRoute } from "wouter";

/**
 * Wrap wouter's <Link> component to ensure that an <a> element is always
 * created. This ensures that you can style a Link and its child component
 * without worrying about the styles being squished together in one component at
 * runtime. It's also better for accessibility, and enables <a>-dependent
 * features like "open in new tab" right-click actions in the browser.
 */
export function Link(props: LinkProps) {
  const { to, href, children, onClick, ...rest } = props;

  // wouter tries to treat mailto links as regular URLs, and it tries to put
  // them into the browser history stack, which fails. So just use plain links
  // in that case.
  if ((to ?? href)?.toLowerCase().startsWith("mailto:")) {
    return <a {...props} />;
  }

  if (!isValidElement(children)) {
    return <_Link {...props} />;
  }

  return (
    <_Link to={to ?? href} onClick={onClick}>
      <a {...rest}>{children}</a>
    </_Link>
  );
}
```

**Comment by molefrog** [comment]
Hi! We addressed this in the newest version, see https://github.com/molefrog/wouter/releases/tag/v3.0.0-rc.2 (link composition)
I didn't have time to work on the library properly dec/jan, but I'll try to make a final release soon. I still have to update the docs to match the new API, but this is taking ages for me sorry.

**Comment by Jaimeloeuf** [comment]
Hey @molefrog please dont feel sorry about this, even though words cannot do justice just how much I deeply appreciate the effort from you and your team building and maintaining open source software like this, thank you for all that you have done!

On another note, the new release looks awesome, thanks for taking into consideration all the feedbacks!

Hope you have a great week ahead!

**Comment by molefrog** [comment]
Hi, the new release is out including the new documentation. Can you take a look:
https://github.com/molefrog/wouter?tab=readme-ov-file#link-hrefpath-

Can I close this issue if everything looks good?

**Comment by justingrant** [comment]
Looks great, thanks!
