### ISSUE TITLE
Docs don't say how to install; no readme on NPM page

### ISSUE THREAD

**Issue by kevin51jiang** [molefrog/wouter#418]
First of all, thanks for the work on wouter! Love the simplicity.

I think the docs are missing something, namely a copy-pasteable code block that says

```sh
npm install wouter
```

that just makes it much more convenient when I want to install this package. Although I know the package is called wouter, I don't know if it's under some org (e.g. @kevin51jiang/wouter).

---

Also, on the NPM page it seems like it doesn't have a README, would be great if one could be added.
<img width="841" alt="image" src="https://github.com/molefrog/wouter/assets/33907581/1007a60c-45a9-4798-a76e-e01b98fbeec9">

**Comment by molefrog** [comment]
Added installation instructions to the README and fixed the build (because it's monorepo, the README file was in the root workspace package and not `wouter`). Thank you!
