### ISSUE TITLE
import/no-unresolved eslint error being raised on Wouter 3.0.x

### ISSUE THREAD

**Issue by mjfwebb** [molefrog/wouter#423]
Hello! Thanks for Wouter, I love using it.

I was migrating to Wouter 3 and noticed I had a relatively minor error being reported from an eslint rule `import/no-unresolved`:

```
Unable to resolve path to module 'wouter'.
```

This seems to be related to this issue: https://github.com/import-js/eslint-plugin-import/issues/2132

From their discussions, it seems the problem is that the Wouter's `package.json` does not have a `main` entry. I confirmed that adding `"main": "esm/index.js",` to the Wouter `package.json` resolved this error.

Is this something you would be willing to address? If so, I'm happy to make a PR.

Otherwise, I can simply ignore the error, but it might be something that others come across as well.

**Comment by molefrog** [comment]
Hi! Yep, this makes sense. Feel free to open a PR. Make sure the modify wouter-preact as well.

**Comment by molefrog** [comment]
Hey @mjfwebb let me know if it fixed the issue.

**Comment by mjfwebb** [comment]
Yep, @molefrog it's fixed in 3.0.2! Thanks!
