### ISSUE TITLE
Intercept location change with custom hook swallows state

### ISSUE THREAD

**Issue by maciossek** [molefrog/wouter#425]
Hello there!

I am struggling to understand where the history state get's "swallowed" when having a custom hook. I forked the initial example and updated the dependencies. Currently logging the `history.state` or the `useHistoryState()` and sadly being `null` when using the custom hook. It works as intended when I remove the custom hook.

This is related to #39.

[codesandbox](https://codesandbox.io/p/sandbox/wouter-demo-interruptible-transition-forked-yqw3zg?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clt4iukge00063b6hf91g5hk5%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clt4iukge00023b6hl1hkxzjj%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clt4iukge00033b6hcxxkqzlo%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clt4iukge00053b6hexsd7s4w%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clt4iukge00023b6hl1hkxzjj%2522%253A%257B%2522id%2522%253A%2522clt4iukge00023b6hl1hkxzjj%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clt4iukge00053b6hexsd7s4w%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clt4iukge00043b6hu5he19nk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252Fabout%2522%257D%255D%252C%2522id%2522%253A%2522clt4iukge00053b6hexsd7s4w%2522%252C%2522activeTabId%2522%253A%2522clt4iukge00043b6hu5he19nk%2522%257D%252C%2522clt4iukge00033b6hcxxkqzlo%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clt4iukge00033b6hcxxkqzlo%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by molefrog** [comment]
`state` is one of the options of `setLocation` so you have to proxy the second argument (or better, rest of args):

```
const useLocationWithConfirmation = (...args) => {
  const historyState = useHistoryState();

  const [location, setLocation] = useBrowserLocation(...args);

  const ctx = useContext(LockContext);

  console.log(history.state, historyState);

  return [
    location,
    (newLocation, ...options) => {
      let perfomNavigation = true;
      if (ctx.lock) {
        perfomNavigation = window.confirm(ctx.message || "Are you sure?");
      }

      if (perfomNavigation) setLocation(newLocation,  ...options);
    },
  ];
};
```

**Comment by maciossek** [comment]
Wonderful, I totally missed that. Many thanks for the super quick reply! Also a big thank you for writing the lib!
