### ISSUE TITLE
Is there a way to bypass the `base` of the Router in a Link?

### ISSUE THREAD

**Issue by jeerbl** [molefrog/wouter#431]
I tried `<Link href="~/path">...</Link>` but the `~` does not seem to bypass the `base` of the router. On top of that, when specifying an `HrefFormatter` to the router to bypass manually in the Router configuration, the `~` character is not included in the `link`.

Is there any other way to achieve this? Let me know if this need more clarification.

Jérôme

**Comment by molefrog** [comment]
Hi @jeerbl, could you share a piece of code? This is supposed to work.

**Comment by molefrog** [comment]
> but the URL displayed in `href` attribute of the `<a>` element is actually `/sub/url`.

That's because you have a custom hrefs formatter, if you remove it you the href will be `/url` isn't that something you want?

**Comment by molefrog** [comment]
the `hrefs` only affects the `href` attribute rendered and it is mostly needed for server-side rendering (e.g. when you use hash-based routing, the html rendered must be `<a href="#/" />` and not `<a href="/" />`). During runtime, it does nothing.

**Comment by molefrog** [comment]
> My question is—if I want the `LinkComponent` to always go to `/sub/url`, even when used on line 17, what would you suggest?

Just use `~/sub/url`. The base path for default router is always `/`

**Comment by molefrog** [comment]
Hi @jeerbl is this issue still relevant?

**Comment by jeerbl** [comment]
Hi @molefrog, actually it isn't! Closing this issue :)
