### ISSUE TITLE
build bug

### ISSUE THREAD

**Issue by huazhuangnan** [molefrog/wouter#435]
RollupError: [commonjs--resolver] node_modules/wouter/esm/react-deps.js (8:2): Identifier "useRef" has already been declared

**Comment by molefrog** [comment]
I can't confirm this error, can you provide more details? As I can see, in `wouter/esm/react-deps.js` `useRef` is only declared once.

**Comment by huazhuangnan** [comment]
Yes, Rollup builds will fail!
