### ISSUE TITLE
Bug with switch, dynamic segments and popstate

### ISSUE THREAD

**Issue by jeetiss** [molefrog/wouter#45]
Make [codesandbox](https://codesandbox.io/s/wouter-bug-with-switch-hoet9)

And video with reproducing bug 🦖

![Запись экрана 2019-07-07 в 0 09 27](https://user-images.githubusercontent.com/6726016/60761171-b91a2300-a04b-11e9-9327-61b9a4f3ca9b.gif)

**Comment by molefrog** [comment]
Hey @jeetiss, thanks for reporting. 
My guess is that this isn't connected to the popstate event, but rather to a fact that the rendering order of `Switch` and nested `Route` isn't deterministic: while normally the rendering order is as following:
- Switch renders
- Route renders 

when an event happens outside of the event handling routine it could happen that the inner Route renders first and then the corresponding Switch component. I have one possible solution in mind, but I first need to reproduce this as a regression test.

**Comment by molefrog** [comment]
Closed via #46

**Comment by molefrog** [comment]
@jeetiss Released the new version `v2.1.1`, feel free to upgrade!
