### ISSUE TITLE
Meta: Add `.gitattributes` file

### ISSUE THREAD

**Issue by JonahPlusPlus** [molefrog/wouter#451]
Prettier formats files with line endings of `lf`, which causes problems for Windows developers who have `autocrlf` enabled. (See https://prettier.io/docs/en/options#end-of-line)

There needs to be a `.gitattributes` file with `* text=auto eol=lf` to disable the `autocrlf`.

**Comment by JonahPlusPlus** [comment]
(I didn't bother adding this to #450 since it would result in a bunch of files being changed)

**Comment by molefrog** [comment]
Sounds good to me! Could you make a PR please?
