### ISSUE TITLE
Transpile the build for older browsers.

### ISSUE THREAD

**Issue by abhishekoza** [molefrog/wouter#454]
Wouter lib uses optional chaining which is not supported by older browsers. Can we transpile it while building so its compatible?

**Comment by molefrog** [comment]
Hi! We support ES2020 onward (the readme says 2019, but that is a typo. we'll fix it, thanks) and don't ship transpiled code. Is there a chance you can configure your bundler to transpile it for you?

**Comment by abhishekoza** [comment]
I can transpile on my end. I just thought to bring this to attention as I
thought its very common to have a build where code is transpiled. Thank you
