### ISSUE TITLE
Consider exposing `matchRoute` helper function

### ISSUE THREAD

**Issue by acelaya** [molefrog/wouter#455]
I wanted to ask if you would consider exposing the [`matchRoute`](https://github.com/molefrog/wouter/blob/6abe3832430c0b564ca0054f79ea5e2ff592a1af/packages/wouter/src/index.js#L81) helper function that is internally used by `useRoute` and `Switch`.

I'm trying to create a custom hook which receives a list of routes in order to check which one matches, but this list of routes is dynamic, so it's not possible to call `useRoute` a bunch of times, since it needs to loop over the list of routes.

However, if `matchRoute` was exported by this package, it would allow userland programmatic logic like this:

```ts
import { matchRoute, useLocation, useRouter } from 'wouter-preact';

function useMatchingRoute(candidates: string[]): [string, Record] | undefined {
  const { parser } = useRouter();
  const [location] = useLocation();

  return useMemo(() => {
    for (const route of candidates) {
      const [matches, params] = matchRoute(parser, route, location);
      if (matches) {
        return [route, params];
      }
    }

    return undefined;
  }, [location, parser, candidates]);
}
```

I can provide a PR if you are ok with this.

**Comment by molefrog** [comment]
> I wanted to ask if you would consider exposing the [`matchRoute`](https://github.com/molefrog/wouter/blob/6abe3832430c0b564ca0054f79ea5e2ff592a1af/packages/wouter/src/index.js#L81) helper function that is internally used by `useRoute` and `Switch`.
> 
> I'm trying to create a custom hook which receives a list of routes in order to check which one matches, but this list of routes is dynamic, so it's not possible to call `useRoute` a bunch of times, since it needs to loop over the list of routes.
> 
> However, if `matchRoute` was exported by this package, it would allow userland programmatic logic like this:
> 
> ```ts
> import { matchRoute, useLocation, useRouter } from 'wouter-preact';
> 
> function useMatchingRoute(candidates: string[]): [string, Record] | undefined {
>   const { parser } = useRouter();
>   const [location] = useLocation();
> 
>   return useMemo(() => {
>     for (const route of candidates) {
>       const [matches, params] = matchRoute(parser, route, location);
>       if (matches) {
>         return [route, params];
>       }
>     }
> 
>     return undefined;
>   }, [location, parser, candidates]);
> }
> ```
> 
> I can provide a PR if you are ok with this.

Hey @acelaya, thank you for suggesting this. I think it makes a lot of sense, so feel free to open a pull request.

**Comment by acelaya** [comment]
> Hey @acelaya, thank you for suggesting this. I think it makes a lot of sense, so feel free to open a pull request.

Just created it https://github.com/molefrog/wouter/pull/456

**Comment by molefrog** [comment]
Just published the new version.
