### ISSUE TITLE
break out of nest and keep base

### ISSUE THREAD

**Issue by huanent** [molefrog/wouter#459]
Hi 
I have this route config

```
<Router base="/admin">
    <Route path="/account" nest>
        <Route path="/login"/>
    <Route>
    <Route path="/home" nest>
        <Route path="/projects"/>
    <Route>
</Router>
```
I would like jump to ```/admin/home/projects``` from ```/admin/account/login```, so I need use ```setLocation('~/admin/home/projects')```
Is there a way to keep base and break out of nest?
like ```setLocation('@/home/projects')``` -->"/admin/home/projects"

**Comment by molefrog** [comment]
No, there is no way to make it work like that at the moment. Actually, `<Route nest>` internally creates a new Router with a special `base` prop, so we can't really distinguish between nested routes and routers with base attribute. The `~` modifier only works with top-level paths.

**Comment by huanent** [comment]
I understand. Thank you for your answer.
