### ISSUE TITLE
Path component with prefixes is not supported in v3

### ISSUE THREAD

**Issue by Gerhut** [molefrog/wouter#462]
Hi.

I previously set up a few of routes with prefixes, like

```jsx
<Route path="/:project" component={ProjectPage} />
<Route path="/@:user" component={UserPage} />
<Route path="/~:org" component={OrgPage} />
```

After upgrading to v3, all of them are routed to the project page.

Any plan to fix this regression?

**Comment by molefrog** [comment]
In v3, we migrated to [regexparam](https://github.com/lukeed/regexparam) in favour of our custom parser which was difficult to maintain. This was a breaking change, so some things stopped working, however you can still support this route prefixes by opting in to path-to-regexp (it adds some extra KBs). [You can use this guide](https://github.com/molefrog/wouter?tab=readme-ov-file#are-strict-routes-supported) to integrate path-to-regexp.
