### ISSUE TITLE
Publish additional package for Preact

### ISSUE THREAD

**Issue by molefrog** [molefrog/wouter#48]
With proper peer dependencies. See: https://twitter.com/m_kruschke/status/1148655449417367552

**Comment by cedeber** [comment]
I think the new private `preact/package.json` on the pull request #55 should solve the problem. I did it like preact hooks where you need to import `preact/hooks`. So you need to install wouter once and do import `wouter` or `wouter/preact` as wished.

**Comment by molefrog** [comment]
@cedeber Well, yes, but this won't solve the problem with different peer dependencies for react and preact versions. 
I plan to make the `preact/package.json` public and rename it to `@wouter/preact`. So whenever I publish a new version a corresponding Preact version is published as well. Another idea is to keep preact sources in the original package, so that both ways work:

```js
// this will require React as a peer dep
import * from "wouter/preact"; 

// this will only require Preact
import * from "@wouter/preact";
```

**Comment by cedeber** [comment]
I wonder if we really need wouter as peer dependency into the `/preact` folder as the files are copied at installation anyway. Does TypeScript also look into the root folder if we import from `wouter/preact` ? If no, then React won't be a peer dependency anymore.

**Comment by molefrog** [comment]
The Preact-only package is now published under the name `wouter-preact` (an npm scope `@wouter` was taken).
