### ISSUE TITLE
`matchRoute` export is missing in `wouter-preact`

### ISSUE THREAD

**Issue by remziatay** [molefrog/wouter#484]
`matchRoute` helper was exported recently with https://github.com/molefrog/wouter/pull/456 from `wouter` package but `wouter-preact` is missing this export

**Comment by molefrog** [comment]
Hmm... I can see that it is exported here https://www.npmjs.com/package/wouter-preact?activeTab=code in file `esm/index.js` at the very bottom.

**Comment by remziatay** [comment]
> Hmm... I can see that it is exported here https://www.npmjs.com/package/wouter-preact?activeTab=code in file `esm/index.js` at the very bottom.

Oh sorry, then I think the type is not exported. It's not listed in `index.d.ts`

![image](https://github.com/user-attachments/assets/c2f84560-f48a-4313-b6e8-dc53e8369792)

**Comment by molefrog** [comment]
Right, we forgot to export the type. I've fixed this in 3bbf10a40de1b12776364b3c891eb08a74d7330a

You can upgrade to the latest version and this error should be gone.
