### ISSUE TITLE
State of children is preserved between Routes

### ISSUE THREAD

**Issue by mr-moon** [molefrog/wouter#496]
https://codesandbox.io/p/sandbox/naughty-bohr-6h998w

If you navigate through routes while changing the counter, the sate is preserved within routes? Looks like a bug to me, especially considering the View is updated, but the sate of child components - no.

**Comment by mr-moon** [comment]
The workaround with CS above is to wrap the `<Counter />` in a different element, so that domain tree is different between routes.
```javascript
<Route path="/view1">
  <Fragment>
    View 1
    <div> 
      <Counter />
    </div>
   </Fragment>
</Route>
```
If you wrap both counters of `/view1` and `/view2` routes - the state will be shared again.
And it's reproducible in both, React and Preact.

**Comment by molefrog** [comment]
Hi @mr-moon, this doesn't look like a bug to me but rather the implementation detail. If I'm not mistaken, Next.js also doesn't remount page components. I suppose it is done for the sake of performance.

**Comment by mr-moon** [comment]
Hm. Thanks for the info @molefrog. Bummer. But, ok, noted. This prevented me from defining loaders as:
```js
<Route path='/companies'>
  <Fetcher loader={comapniesLoader}>
      {(c: TCompany[]) => <Companies companies={c} />}
  </Fetcher>
</Route>
```
