### ISSUE TITLE
Minor type tweaks to cover edge cases

### ISSUE THREAD

**Issue by molefrog** [molefrog/wouter#56]
Hey @StrayFromThePath @StrayFromThePath I'm super excited to have types finally in the project! I managed to spent some time reading the sources and although I'm not a TS user I've got some feedback I thought I need to share with you. 

### Proper `Params` type
The current `Params` type is a union of hash or `null`. This works fine for the `Match` type which can represent either `[true, { ... }]` or `[false, null]`, however this also assumes that the render prop can contain the null as a first argument [here](https://github.com/molefrog/wouter/blob/master/index.d.ts#L22). I think we can narrow the type even further, because the render prop always guarantees that the argument is a valid object. 

So how can this be solved? I suggest we make the Params type to always be an object and mark that the match result could contain null:
```js
type Params = { [paramName: string]: string }

// it this a real TypeScript code? :) I'm not sure, but you get the idea
type Match = [boolean, Params | null];

// or is this even possible:
type Match = [true, Params] | [false, null];
```

### Remove `match` props from `Route`
This prop is an internal thing used by the switch, so it's not part of the public API. I suggest we either remove it or change the type, since it's not a boolean anymore, but `Match`. But I think it's easier to just remove this. 

### Proper type of `children` in `Router`
As @StrayFromThePath pointed out in #54, some components need proper types to support mixed React nodes. The current type of the `children` prop in `Router` is `ReactElement | ReactElement[];`, but this makes it impossible to use something like:

```js
<Router>
  Hello, this is an <Application />
  We also have <Footer /> and some {1337} numbers here.
</Router>
```
 
Same applies to `Link`. Generally speaking, anything that `React.Provider` accepts should work here as well. 

Let me know what you guys think and keep up with the good work!

**Comment by Ty3uK** [comment]
> ```js
> // it this a real TypeScript code? :) I'm not sure, but you get the idea
> type Match = [boolean, Params | null];
> ```

Yep, it's corrent TS code

**Comment by polRk** [comment]
```typescript
type Params = { [paramName: string]: string }

type MathWithParams = [true, Params]
type MathWithoutParams = [false, null]

type Match = MathWithParams | MathWithoutParams;

```

**Comment by polRk** [comment]
It's better, because i can use condition statement and get valid type

```typescript

interface MyInterface { name: string }

const [match, params] = useRoute<MyInterface>("/users/:name");

if (math) {
  params.name
}

```

**Comment by Ty3uK** [comment]
@polRk yep, good catch 👍

**Comment by molefrog** [comment]
@Ty3uK @StrayFromThePath Turns out, `ReactNode` type includes `ReactFragment`, so there is actually no need to write `ReactNode | ReactNode[]`. Fixed it in https://github.com/molefrog/wouter/pull/62/commits/66ceba10aa15f97d7f035da0a4cba4416bfd4824
