### ISSUE TITLE
Url Params decode 

### ISSUE THREAD

**Issue by sumohammed** [molefrog/wouter#57]
Hello, 

Been having some issues with params values in the sense that with long text params the space symbols still stays in the props value extracted and i have to use decodeURIComponent.

Is there anyway props value could be formatted by default?

**Comment by molefrog** [comment]
Hi, 
@sumohammed is it possible to provide an example? It would help a lot!

**Comment by molefrog** [comment]
@sumohammed Ok, I think I understand the problem:
The url `/app/:name` with `/app/some name` gives you `{ "name": "some%20name" }`.

Our current implementation does not support this behaviour, but you can easily extend the location hook to add a support for it before the new version is released:

https://codesandbox.io/s/wouter-decodeuricomponent-tfi2g
