### ISSUE TITLE
useCallback for setLocation

### ISSUE THREAD

**Issue by neves** [molefrog/wouter#69]
Instead of anonymous function, returns a useCallback https://github.com/molefrog/wouter/blob/master/use-location.js#L16

`const [, setLocation] = useLocation()` setLocation should be the same on each render

**Comment by ifokeev** [comment]
+

**Comment by molefrog** [comment]
@neves @ifokeev That's a good point indeed. Thanks for bringing that up!
Going to let you guys know when the fix is ready.
