### ISSUE TITLE
Allow passing state to link/setLocation

### ISSUE THREAD

**Issue by destructobeam** [molefrog/wouter#75]
Would it be possible to support the following using the browser's `history.state` API, optionally allowing `history[method](stateObj, 0, to)`, instead of always using `history.[method](0, 0, to)`?

e..g.

```jsx
<Link href="/" state={{ exampleState: true }}>Link</Link>
```
and
```js
const [location, setLocation] = useLocation();

setLocation("/", { exampleState: true });
```

Not sure where the accessor makes the most sense, maybe something like:
```js
import { useRouterState } from 'wouter';

const routerState = useRouterState();
```

Thanks!

**Comment by molefrog** [comment]
@destructobeam Hi and thanks for the issue! 

I see that this is something that we intentionally don't support in wouter, but since `pushState` supports it, why wouldn't we implement this? However, my concern is if it's actually going to be used by developers. 

Can you provide a use case? Thanks!

**Comment by destructobeam** [comment]
Hey @molefrog,

Do you know the rationale is behind the intentional lack of support? I’m curious as to why that would be.

I think it’s a nice interface for passing animation names and vars between routes, and anything else you need to pass additional parameters to without gumming up the URL with params or necessitating a global state management lib. It also persists across browser native back/forward buttons which is nice.

It makes sense to me to have it as part of the wouter lib as the history API methods are already utilised, so it would potentially be less overhead and a cleaner API than an isolated solution that would require wrapping each component? But I could be missing something here.

Cheers!

**Comment by molefrog** [comment]
The discussion moved to #102
