### ISSUE TITLE
404 on direct request to route

### ISSUE THREAD

**Issue by talentlessguy** [molefrog/wouter#82]
Routes only work with `<Link>` but when you go directly to a route it just throws 404. What's about adding support for direct requests like in React Router?

**Comment by molefrog** [comment]
Well, it should work with any type of navigation, even those that are fired outside of a link. Can you provide an example?

**Comment by talentlessguy** [comment]
Example is here: [v1rtl.site](https://v1rtlsite-jq0b7knaj.now.sh)

FIrst try to click on "Art", then "More stuff". It loads normally.

![image](https://user-images.githubusercontent.com/35937217/63650576-9acfca00-c754-11e9-9477-c47469f9059c.png)

![image](https://user-images.githubusercontent.com/35937217/63650578-a1f6d800-c754-11e9-90bb-78818b393642.png)

Now let's try to go to page directly.

![image](https://user-images.githubusercontent.com/35937217/63650585-b509a800-c754-11e9-8cf6-27fc551badb2.png)

Code of Router is here:

```jsx
<Fragment>
    <Route path="/" exact component={Main} />
    <Route path="/art" component={Art} />
    <Route path="/gif" component={Gif} />
    <Route path="/web" component={Web} />
  </Fragment>
```

**Comment by molefrog** [comment]
Well, that's because you have to tell Now.sh to serve your application's index.html on every request different from just `/`. That's the way routing in SPAs works, so the issue is not in wouter, but rather in your website deployment setup.

Not sure, but I think here is what might help:
https://zeit.co/docs/v2/advanced/configuration#routes

**Comment by molefrog** [comment]
Oh, and by the way, no need to mark route as exact. A Route in wouter always matches an entire string.

**Comment by talentlessguy** [comment]
> Oh, and by the way, no need to mark route as exact. A Route in wouter always matches an entire string.

Oopsie, I just moved from React Router :smile:, will remove `exact`. And yup, problem is with Now.sh, closing the issue. Sorry for interruption

**Comment by eti0** [comment]
just in case, for anyone that stumbles upon this same issue while using vercel.

simply add this to `vercel.json` :
```json
"rewrites": [
    {
        "source": "(.*)",
        "destination": "/index.html"
    }
]
```
after that, you should be good to go :)
