### ISSUE TITLE
The regex routes cause errors

### ISSUE THREAD

**Issue by slavagoreev** [molefrog/wouter#93]
If we will try to use `path-to-regexp` package it will break the router just because it uses another semantics. I have written a custom `makeMatcher` function to make it possible to use it. It is not perfect but at least doesn't break the system. 

**The `getRegexp(pattern);` function doesn't return tuple but just regex in the `path-to-regexp` package**

Also, this workaround allows creating i18n routes like `/:lang(en|es|pt)/posts/:id`.

```typescript
function makeMatcher(makeRegexpFn = pathToRegexp) {
  const cache: { [key: string]: RegExp } = {};

  // obtains a cached regexp version of the pattern
  const getRegexp = (pattern: string) =>
    (cache[pattern]) || (cache[pattern] = makeRegexpFn(pattern));

  return (pattern: Path, path: Path) => {
    const regexp = getRegexp(pattern);
    const found = pattern.match(/:(\w+)/ig);
    const keys = found ? found.map(el => el.substr(1)) : [];
    const out = regexp.exec(path);

    if (!out) return [false, null];

    // formats an object with matched params
    const params = keys.reduce((params, key, i) => {
      params[key] = out[i + 1];
      return params;
    }, {});

    return [true, params];
  };
}
...

<Router matcher={makeMatcher(pathToRegexp)}>
```

**Comment by molefrog** [comment]
@slavagoreev Hi! Thanks for the issue. 

I guess we changed the `makeMatcher` interface in one of the first releases to save a couple of extra bytes. The README should be updated however.

**Comment by molefrog** [comment]
That's where we dropped it: https://github.com/molefrog/wouter/pull/42

I'll try to think of an adapter to use with `pathToRegexp`.

**Comment by molefrog** [comment]
Check out this demo:
https://codesandbox.io/s/wouter-path-to-regexp-strict-rq72c

**Comment by omgovich** [comment]
Seems to me that we could close the issue.

**Comment by molefrog** [comment]
@omgovich Could add a TOC entry to the readme? https://github.com/molefrog/wouter#are-strict-routes-supported
